### ISSUE TITLE
How can I edit selected file on double-click ?

### ISSUE THREAD

**Issue by Silnar** [Shougo/vimfiler.vim#134]
I was using NERDTree earlier and found "double-click and edit" very useful when I wanted just to take a look on code in several files.
Is it possible to change this internal vimfiler mapping in my .vimrc ? Or maybe there is another way to quickly browse files with mouse ?

**Comment by p0deje** [comment]
I believe the most simple solution now is:

```vim
nmap <silent><buffer> <2-LeftMouse> <Plug>(vimfiler_smart_l)
```

**Comment by Silnar** [comment]
It worked when I added it like this:

```viml
autocmd FileType vimfiler nmap <silent><buffer> <2-LeftMouse> <Plug>(vimfiler_smart_l)
```

Thanks :smile:
