### ISSUE TITLE
Add action: horizontal split edit file

### ISSUE THREAD

**Issue by ajpaulson** [Shougo/vimfiler.vim#139]
currently there are 2 edit file actions - default:

```
e = vimfiler_edit_file
```

and

```
E = vimfiler_split_edit_file
```

the second one seems to open a vsplit by default - I think it would be useful to add an action such as 

```
vimfiler_horiz_split_edit_file 
```

or make horizontal the default for 

```
vimfiler_split_edit_file 
```

and add 

```
vimfiler_vsplit_edit_file
```

to follow the default split and vsplit behavior of vim

**Comment by kesco** [comment]
The mapping:
```vimrc
autocmd FileType vimfiler nnoremap <silent><buffer><expr> S vimfiler#do_action('vsplit')
```
has not came to effect. I try to change it to:
```vimrc
autocmd FileType vimfiler nnoremap <silent><buffer><expr> s vimfiler#do_switch_action('split')
```
and it done.
