### ISSUE TITLE
Feature request - keep alternate buffer when editing another file

### ISSUE THREAD

**Issue by wilywampa** [Shougo/vimfiler.vim#187]
If I'm editing file 1, then open VimFiler and choose to edit file 2, I would like `<C-^>` to return to file 1. Instead, it returns to the VimFiler buffer. I get the behavior I want if I open VimFiler with the `-quit` option, but that breaks the preview action functionality. Is there a way to switch back to file 1 instead of the VimFiler buffer without the `-quit` option?

I also tried `<Plug>(vimfiler_exit)` after `<C-^>` switches back to VimFiler, but that leaves file 2 with no alternate buffer instead of file 1 being the alternate. Calling `call vimfiler#util#alternate_buffer()` at this point switches to another buffer, but not necessarily file 1.

Thanks!

**Comment by vasconcelloslf** [comment]
Hi @Shougo  

I have a similiar problem: when I'm with multiple buffers opened (A, B and C) + vimfiler, when I do a :bn or :bp I just want to cycle through the buffers A, B and C, and not through the vimfiler buffer.

How can I achieve this behaviour?
Thank you.

**Comment by Shougo** [comment]
@vasconcelloslf You can set "setlocal nobuflisted" in vimfiler  buffer.

**Comment by vasconcelloslf** [comment]
Thank you for your fast response, it works very well.
