### ISSUE TITLE
Explorer-Columns don't get it

### ISSUE THREAD

**Issue by NemesisRE** [Shougo/vimfiler.vim#223]
I tried to enable all columns in explorer mode by passing the -explorer-columns option...
I tried:
-explorer-columns=type:size:time -> only see type
-explorer-columns={type:size:time} -> only see type

And is there a way to enable parent (..) in explorer view

regards
Steven

**Comment by Tuxdude** [comment]
Thanks for the vimfiler plugin loving it!

I just tried `VimFiler -explorer -explorer-columns=type -parent`, it works if I try this command the first time. 

If I change the columns option next time without closing the vim process like this:
`VimFiler -explorer -explorer-columns=type:size -parent`, it still shows just the type and not the size. I guess only the very first settings during the session is getting persisted ?

**Comment by Shougo** [comment]
> I guess only the very first settings during the session is getting persisted ?

Yes.  You must close the buffer.
