### ISSUE TITLE
How to delete a file?

### ISSUE THREAD

**Issue by bijancn** [Shougo/vimfiler.vim#232]
I have installed 

```
    Plugin 'Shougo/unite.vim'
    Plugin 'Shougo/vimproc.vim'
    Plugin 'Shougo/vimfiler.vim'
```

via vundle and set

```
let g:vimfiler_as_default_explorer = 1
nmap <buffer> d <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_delete_file)
```

But neither via the file mode of unite nor when im in `:VimFiler` I can delete a file with `d`. I can mark it before with `<space>` or not but I always get `No such action : delete`. What am I doing wrong?

**Comment by collegeimprovements** [comment]
there is a shortcut `gs` for this purpose. You can also use that to toggle `Safe Mode`.
