### ISSUE TITLE
Clobbers default / common mappings

### ISSUE THREAD

**Issue by blueyed** [Shougo/vimfiler.vim#242]
I've noticed that there are several mappings that get clobbered in vimfiler buffers:
- `?` is useful when initiating backward search. It's mapped to help (same for Unite).
- `<Space>` is a great map leader, vimfiler clobbers it for marking files!
- `<C-L>` is a common mapping to move to the right window. It is mapped to `vimfiler_redraw_screen`.

**Comment by jrolfs** [comment]
I'm still having trouble with the `<C-L>` mapping, can you elaborate on what is overriding it?

**Comment by Shougo** [comment]
@jrolfs `:verbose nmap <C-L>`

**Comment by jrolfs** [comment]
Thanks for the insight, when running that command in a 'standard' buffer:
![buffer](http://d.pr/i/nRLt+)

From within a `VimFilerExplorer` buffer:
![VimFilerExplorer buffer](http://d.pr/i/125n8+)

From my `init.vim`:
```viml
" Pane navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-N> <C-W><C-H>
```
I'm still unable to use `<C-L>` to navigate out of the **vimfiler** window to the window to the right of it. I apologize if I'm just misunderstanding how mapping works and am happy to move this question elsewhere if it's not specifically relevant to **vimfiler**.

Thanks!

**Comment by Shougo** [comment]
@jrolfs You can disable vimfiler `<C-l>` mapping using `nunmap <buffer> <C-l>`.
You should learn VimL...

**Comment by jrolfs** [comment]
Yes... I really should (at the very least have a better understanding of mappings). Thanks for your help!
