### ISSUE TITLE
Open file in new tab

### ISSUE THREAD

**Issue by jvillasante** [Shougo/vimfiler.vim#248]
Is there a way to open a file selected in VimFilerExplorer in a new tab?

**Comment by atimholt** [comment]
I can’t get this to work. running `:call vimfiler#do_action('tabopen')` does nothing and echoes nothing while in a vimfiler window.

**Comment by Shougo** [comment]
@atimholt Please read the documentation.
`vimfiler#do_action()` must be used in mappings.

And please read #139
