### ISSUE TITLE
Vimfiler opens "test" directory when opening "test.gpg" with vim-gnupg

### ISSUE THREAD

**Issue by blueyed** [Shougo/vimfiler.vim#256]
I've noticed that `vim test.gpg` (where test.gpg does not exist) will make Vimfiler open the existing "test" directory in [vim-gnupg](https://github.com/jamessan/vim-gnupg)'s `GPGRecipients_test.gpg` buffer/window.

This is triggered by `g:vimfiler_as_default_explorer=1`.

See https://asciinema.org/a/15000 - where it fails with `test.gpg`, but works with `tst.gpg` (because there is no folder `tst`).

The recipient buffer is handled/opened via https://github.com/jamessan/vim-gnupg/blob/master/plugin/gnupg.vim#L733 (called via https://github.com/jamessan/vim-gnupg/blob/master/plugin/gnupg.vim#L430-L444).

**Comment by Shougo** [comment]
No response.
