### ISSUE TITLE
highlight (conceal) problem with multi-byte icons

### ISSUE THREAD

**Issue by itchyny** [Shougo/vimfiler.vim#259]
```vim
set nocompatible
filetype off
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
set rtp+=/path/to/unite
set rtp+=/path/to/vimfiler
filetype plugin indent on
syntax enable
```
With the above vimrc, the conceal characters are visible.
![screen shot 2015-01-21 at 9 25 46 pm](https://cloud.githubusercontent.com/assets/375258/5836121/395a19b2-a1b4-11e4-9017-631353db864f.png)

**Comment by Shougo** [comment]
Confirmed.  It is bug.

**Comment by Shougo** [comment]
Fixed.

**Comment by itchyny** [comment]
Thank you.
