### ISSUE TITLE
highlight problem with multi-byte filenames

### ISSUE THREAD

**Issue by itchyny** [Shougo/vimfiler.vim#260]
The syntax in the dates is broken with multi-byte filenames.
![screen shot 2015-01-28 at 5 06 08 am](https://cloud.githubusercontent.com/assets/375258/5926065/84c5ee3e-a6ab-11e4-9347-a58370f01100.png)
vimrc
```vim
set nocompatible
filetype off
set rtp+=/path/to/vimfiler
set rtp+=/path/to/unite
filetype plugin indent on
syntax enable
```
With the latest unite/vimfiler.

**Comment by Shougo** [comment]
It is known problem.
Unfortunatelly, I cannot fix it.
Pull request is wellcome.

**Comment by Shougo** [comment]
I will try another solution.

**Comment by Shougo** [comment]
I fixed the problem in syntax branch.

**Comment by itchyny** [comment]
そのブランチ、次のアイコンの設定でうまく動きます？
```vim
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
```

**Comment by Shougo** [comment]
@itchyny It is works in Vim 7.4.569.   Yes, it is not works in Vim 7.4.608.
It seems Vim 7.4.582 degrade.   Can you check it?  I have not much time.

http://ftp.vim.org/vim/patches/7.4/7.4.582

**Comment by Shougo** [comment]
I get the problem.  It is Vim 7.4.577 degrade.
I will report the problem in Vim-jp issues.

http://ftp.vim.org/vim/patches/7.4/7.4.577

**Comment by itchyny** [comment]
It seems that the branch `syntax` works well after Vim 7.4.651.

**Comment by Shougo** [comment]
Yes.  It is fixed.

**Comment by itchyny** [comment]
Thanks for fixing this issue.
