### ISSUE TITLE
Use `'wildignore'` setting for `g:vimfiler_ignore_pattern`

### ISSUE THREAD

**Issue by blueyed** [Shougo/vimfiler.vim#261]
The following could be used to use Vim's defaul settings and options for `g:vimfiler_ignore_pattern`:

    '\(\~\|\.o\|\.swp\|\.obj\)$' " based on Vim's default for 'suffixes'.
    \ . '\|' . substitute(escape(&wildignore, '~.*$^'), '\\\@<!,', '$\\|', 'g') .'$' " &wildignore, ORed (split on (not escaped) comma).

(Source)[https://github.com/tomtom/tmru_vim/blob/master/plugin/tmru.vim#L183-L184].

My wildignore settings are as follows, and it would be useful if Vimfiler would pick them up:

    set wildignore+=*.o,*.obj,.git,.svn
    set wildignore+=*.png,*.jpg,*.jpeg,*.gif,*.mp3
    set wildignore+=*.sw?
    set wildignore+=*.pyc,__pycache__

**Comment by Shougo** [comment]
Implemented.
Please use "matcher_ignore_wildignore".

**Comment by blueyed** [comment]
Thanks!

For reference:

    let g:vimfiler_ignore_filters = ['matcher_ignore_wildignore']
