### ISSUE TITLE
vimfiler bindings now take immediate precedence over my own.

### ISSUE THREAD

**Issue by atimholt** [Shougo/vimfiler.vim#262]
I made \<space> my leader key, and now I can’t access many of my custom vim bindings. Vimfiler did not used to act this way.
With a bit of experimenting, I have narrowed it down to changeset 23a9164688ec116c45e8b326afa40b64972c4c4f. It has the commit message “Add \<nowait> for vimfiler mappings”, which makes the cause fairly obvious.
As this seems to be desired behavior (FWIW, I always felt hardwired mappings that commandeer all possibility of control away from the user were a big no no), would an if-guard checking for a user-set setting variable be in order? See if the user wants \<nowait>.
I’m willing to talk more about the issue. Like, will the change only happen if I make it myself? What kind of change would be too sloppy? (Like, duplicating the mappings for each branch of the if is ugly, would something involving `execute` statements be acceptable?) Or do you simply have strong reasons to want to leave it the way it is? Am I thinking about this too hard?

For now, I’ll probably just rollback my installation.

**Comment by Shougo** [comment]
It is feature and I don't want to change it.
If you want to use your `<Space>` features, you should use `nunmap <buffer><Space>` in FileType vimfiler autocmd.

**Comment by Shougo** [comment]
> Or do you simply have strong reasons to want to leave it the way it is? Am I thinking about this too hard?

It is because User keymappings conflicting wait problem.  It is weired.
