### ISSUE TITLE
Window's status line becomes empty after "choose"

### ISSUE THREAD

**Issue by tc0312** [Shougo/vimfiler.vim#264]
Hi,

When a file is opened in vimfiler with multiple windows, vimfiler will ask for which windows to choose.
After choosing the windows, vimfiler clears the statusline for windows, instead of restoring the original statusline.
This happens only when I try to open a already opened file in vimfiler

![image](https://cloud.githubusercontent.com/assets/8400790/6539648/5d169258-c42e-11e4-9bde-df556e68c4d7.png)

**Comment by Shougo** [comment]
Unfortunatelly, I cannot reproduce the problem.
Please upload minimal .vimrc and reproduce ways.

**Comment by blyoa** [comment]
I reproduced the problem.

* Environment Information

 * OS: Windows 7 64bit
 * Vim version: 7.4.648 (modified by kaoriya) 64 bit

* Minimal vimrc 

```
if has('vim_starting')
    set runtimepath+=~/.vim/bundle/unite.vim
    set runtimepath+=~/.vim/bundle/vimfiler
    set runtimepath+=~/.vim/bundle/vimproc.vim
endif
```

* Reproducable ways from Vim starting
 0. startup Vim
 1. split window (:split or :vsplit)
 2. execute VimFilerExplorer (:VimFilerExplorer)
 3. choose a file
 4. press enter
 5. choose window
 6. all statuslines are cleared except the statusline of chosen window

![reproduce](https://cloud.githubusercontent.com/assets/9126033/7100435/8df336de-e05c-11e4-8369-027ca69ce40f.gif)

**Comment by Shougo** [comment]
Fixed.
