### ISSUE TITLE
Add auto refresh for vimfiler:explorer while resizing a split

### ISSUE THREAD

**Issue by luishdez** [Shougo/vimfiler.vim#265]
Currently it looks that if you resize the window in gvim / macvim vim filer auto refresh the content, but if you resize the split it doesn't happen ( see screenshot )

![vim-filer-refresh](https://cloud.githubusercontent.com/assets/38347/6568342/47fae090-c6d6-11e4-9499-dc21066aa73a.png)

Thanks for sharing this great plugin!

**Comment by Shougo** [comment]
Impelmented.
