### ISSUE TITLE
Jumbled up characters with the shell

### ISSUE THREAD

**Issue by gerroon** [Shougo/vimfiler.vim#271]
Hi

I was going through the shortcuts and I see that I can open a shell, cool. I press "H" (while in vimfiler explorer). A shell opens but with jumbled up characters.

![vimfile](https://cloud.githubusercontent.com/assets/8519469/6755611/609a3636-cef2-11e4-90cd-4ccf571028a0.jpg)

I am on Debian 64bit using Gvim.

**Comment by Shougo** [comment]
It is feature.
Because, if you don't install vimshell, vimfiler use `:shell`.
But `:shell` don't support color features.

**Comment by gerroon** [comment]
@Shougo 

Thanks for your reply. I will get the plugin.
