### ISSUE TITLE
Combine vimfiler_new_file and vimfiler_make_directory

### ISSUE THREAD

**Issue by kba** [Shougo/vimfiler.vim#272]
I would like to extend the `vimfiler_new_file` command to execute the `vimfiler_make_directory` command if the entered filename ends with a slash (a la NERDTree).

Before I dig into the code I wanted to ask if that functionality is already there or whether there's a trivial mapping to achieve that.

Thanks for all the work on you plugins, Shougo, much appreciated!

**Comment by trungphan** [comment]
Is it possible to make it even more flexible: for example, if I enter newfolder/newsubfolder/newfile, it should create the new folder and subfolder: newfolder/newsubfolder, and the file: newfile

**Comment by Shougo** [comment]
Implemented.

> Is it possible to make it even more flexible: for example, if I enter newfolder/newsubfolder/newfile, it should create the new folder and subfolder: newfolder/newsubfolder, and the file: newfile

It is already implemented.
