### ISSUE TITLE
Opening in splits not working

### ISSUE THREAD

**Issue by alem0lars** [Shougo/vimfiler.vim#274]
I've added:

```VimL
nnoremap <silent><buffer><expr> v vimfiler#do_switch_action('vsplit')
nnoremap <silent><buffer><expr> s vimfiler#do_switch_action('split')
```

as the documentation says..

However the hotkeys doesn't work. Is something changed that is not in sync with the docs?

Thanks

**Comment by Shougo** [comment]
I tested it.  But it works.
Please upload minimal .vimrc and reproduce ways from Vim starting.

**Comment by Shougo** [comment]
No response.
