### ISSUE TITLE
How to open VimFiler from the files root directory?

### ISSUE THREAD

**Issue by krzkrzkrz** [Shougo/vimfiler.vim#277]
I have VimFiler opened at `~/foo`. Lets say I have a file opened at `~/foo/bar/baz`

When I open VimFiler, is it possible to have it switch to the same directory as where the file is currently opened at. i.e. `~/foo/bar/`?

At the moment, VimFiler opens at `/foo`, since it was first executed from the project directory.

**Comment by Shougo** [comment]
> When I open VimFiler, is it possible to have it switch to the same directory as where the file is currently opened at. i.e. ~/foo/bar/?

`:VimFilerBufferDir`
