### ISSUE TITLE
How can I disable <C-j>?

### ISSUE THREAD

**Issue by krzkrzkrz** [Shougo/vimfiler.vim#278]
How can I disable `<C-j>`, in VimFiler? I currently have `<c-j>` mapped to something else (`nnoremap <c-j> <c-w>j`), and I'd like to use that instead.

I don't mind not being able to see the history directory.

**Comment by Shougo** [comment]
`autocmd FileType vimfiler nunmap <buffer> <C-j>`

**Comment by krzkrzkrz** [comment]
Thank you. This is an awesome plugin!

**Comment by krzkrzkrz** [comment]
I get `Error detected while processing FileType Auto commands for "vimfiler":`

Is `autocmd FileType vimfiler nunmap <buffer> <C-j>` the right setting?

**Comment by Shougo** [comment]
I don't get the error message.
Please upload the error message and your vimfiler configuration.

**Comment by krzkrzkrz** [comment]
This is what I have in `.vimrc`:

    nnoremap <c-e> :VimFilerBufferDir<cr>           " Open VimFiler from the root dir of the current file
    autocmd FileType vimfiler nunmap <buffer> <C-j> " Disable history directory, c+j should be respected
    let g:vimfiler_as_default_explorer = 1

Close and restart Vim. Then hit `c-e`, and the following error shows:

    Error detected while processing FileType Auto commands for "vimfiler":
    E474: Invalid argument

**Comment by krzkrzkrz** [comment]
Ah, it was the comment at the end of `<C-j>` causing the issue. Thanks, works now!
