### ISSUE TITLE
VimFiler opens directories when it shouldn't after shell commands

### ISSUE THREAD

**Issue by wilywampa** [Shougo/vimfiler.vim#281]
This problem was introduced in dd8222a47.

VimFiler will open a directory resulting from any shell command using the quickfix window even if the command ends with '!' to prevent opening a file. Using this .vimrc:
```vim
set nocompatible noshowmode
set hidden hlsearch incsearch
set shortmess+=c
syntax enable
filetype plugin indent on

set runtimepath+=$VIMCONFIG/vimfiles/bundle/vimfiler
set runtimepath+=$VIMCONFIG/vimfiles/bundle/unite
let g:vimfiler_as_default_explorer = 1

let &makeprg = 'find . -maxdepth 0 -type d'
let &errorformat = '%f'
let &grepprg = 'find . -maxdepth 0 -type d'
let &grepformat = '%f'
```

Running either `:make!` or `:grep!` causes VimFiler to open the first directory found.

**Comment by Shougo** [comment]
Please use latest vimfiler.
