### ISSUE TITLE
Error at launching vim with options

### ISSUE THREAD

**Issue by estrategoreal** [Shougo/vimfiler.vim#285]
69bf573 (Apr 8, 2015) のコミットから、下記のように VimFiler を起動オプションにすると vim がエラーを吐き出す。
  $ vim +VimFiler

[エラーログ]
Error detected while processing function vimfiler#view#_redraw_screen:

**Comment by Shougo** [comment]
下記のような .vimrc で試しましたが再現しません。

```vim
set nocompatible

set runtimepath+=~/work/unite.vim
set runtimepath+=~/work/vimfiler.vim
```

最小構成を作ってください。

> [エラーログ]
> Error detected while processing function vimfiler#view#_redraw_screen:

エラーログが不十分です。そのメッセージだけではどこでエラーになったのかわかりません。

> 69bf573 (Apr 8, 2015) のコミットから、下記のように VimFiler を起動オプションにすると vim がエラーを吐き出す。

そのコミットはドキュメントの修正だけです。原因とは言いがたいです。

**Comment by estrategoreal** [comment]
69bf573 から NG になったのはたまたまのようです。

手元の .vimrc を削っていって最小構成で再現させようとしたのですが、再現したりしなかったりで影響を与えているコードまたはプラグインの特定が難しい状況です。vim script がロードされるタイミングに依存しているのでしょうか。

下記場所の .vimrc で
  $ gvim +VimFiler
実行で再現しないか試してみて頂くことは可能でしょうか。
plugin を多数使っていますが。。

https://github.com/estrategoreal/dotfiles/blob/master/.vimrc

**Comment by Shougo** [comment]
量が多すぎて、こちらで試すのは厳しいですね。
エラーメッセージのちゃんとしたログは保存していますか。

**Comment by estrategoreal** [comment]
実行時、下記エラーが gvim の下方に出ます。
これとは別に何かログを見る方法があるのでしょうか。
ちなみに windows / osx / linux どれも同じ挙動です。

--------------------------------------------------------------------------------------------
Error detected while processing function vimfiler#view#_redraw_screen:
line60:
E523: Not allowed here

**Comment by Shougo** [comment]
ふむ。調べてみると、E523 は `set secure` していると出るようです。
ちょっと `set secure` を外してみてもらえますか。

**Comment by estrategoreal** [comment]
set secure 外してみましたが、変わりませんでした。

**Comment by Shougo** [comment]
@estrategoreal 申し訳ないですが、こちらで再現しない以上 @estrategoreal  さんの環境依存ということになりこの問題は直せません。

**Comment by estrategoreal** [comment]
了解です。
もう少し再現できる .vimrc を探ってみます。
進展がありましたらまた書き込みます。
お手数をお掛けしました。

**Comment by estrategoreal** [comment]
下記 .vimrc で再現しましたので、確認してみて頂けないでしょうか。
どうも vim-fugitive が関係していそうです。

---
set nocompatible

if has('vim_starting')
  execute 'set runtimepath+=' . expand('~/.vim/bundle/neobundle.vim')
endif

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleLazy 'Shougo/unite.vim', {
      \ 'commands' : [{ 'name' : 'Unite',
      \                 'complete' : 'customlist,unite#complete_source'},
      \                 'UniteWithCursorWord', 'UniteWithInput']
      \ }
NeoBundleLazy 'Shougo/vimfiler.vim', {
      \ 'depends' : 'Shougo/unite.vim',
      \ 'commands' : [
      \         { 'name' : 'VimFiler',
      \           'complete' : 'customlist,vimfiler#complete' },
      \         'Read', 'Source'],
      \ 'mappings' : '<Plug>',
      \ 'explorer' : 1,
      \ }
NeoBundleLazy 'tpope/vim-fugitive', {
      \ 'commands' : ['Gdiff', 'Gstatus', 'Glog',
      \               'Gwrite', 'Gcommit', 'Gblame'],
      \ }

call neobundle#end()

set laststatus=2
set statusline=%{fugitive#statusline()}

syntax on

filetype plugin indent on

**Comment by Shougo** [comment]
@estrategoreal 下記の .vimrc で試しましたが再現しません。

* 話がややこしくなるので、プラグインマネージャを使わない状態で試してください。

* vim-fugitive で再現するとなると、Vim を実行するディレクトリにもよるような気がします。そこも調査してください。

```vim
set nocompatible

set runtimepath+=~/work/unite.vim
set runtimepath+=~/work/vimfiler.vim
set runtimepath+=~/.cache/neobundle/vim-fugitive/

set laststatus=2
set statusline=%{fugitive#statusline()}

syntax on

filetype plugin indent on
```

**Comment by estrategoreal** [comment]
NeoBundleLazy を使っているのが問題なようです。
NeoBundle 'tpope/vim-fugitive' にすることで解消しました。

確かにロードされていないのに関数を使っているので、ダメですね。。
お手数をお掛けしました。m(_ _)m

**Comment by Shougo** [comment]
了解です。
