### ISSUE TITLE
winwidth option doesn't work

### ISSUE THREAD

**Issue by estrategoreal** [Shougo/vimfiler.vim#286]
下記の通り gvim を "VimFilerExplorer -winwidth" オプションつきで起動しても vimfiler が48 文字分の幅にならない。一度 VimFilerExplorer にカーソル移動すると 48 文字分の幅になる。
  $ gvim +"set columns=179" +"VimFiler -buffer-name=explorer -toggle ~" +tabnew +"VimFilerExplorer -winwidth=48"

1901168 (16 Oct 2014) のコミットからのようです。

**Comment by Shougo** [comment]
この問題も私の環境で再現できず、修正できない状態です。
最小 .vimrc を作成してください。

**Comment by estrategoreal** [comment]
こちらは下記 .vimrc で再現しました。

-----------------
set nocompatible

if has('vim_starting')
execute 'set runtimepath+=' . expand('~/.vim/bundle/neobundle.vim')
endif
call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleLazy 'Shougo/unite.vim', {
      \ 'commands' : [{ 'name' : 'Unite',
      \                 'complete' : 'customlist,unite#complete_source'},
      \                 'UniteWithCursorWord', 'UniteWithInput']
      \ }
NeoBundleLazy 'Shougo/vimfiler.vim', {
      \ 'depends' : 'Shougo/unite.vim',
      \ 'commands' : [
      \         { 'name' : 'VimFiler',
      \           'complete' : 'customlist,vimfiler#complete' },
      \         'Read', 'Source'],
      \ 'mappings' : '<Plug>',
      \ 'explorer' : 1,
      \ }

call neobundle#end()

filetype plugin indent on

**Comment by Shougo** [comment]
再現しました。修正します。

**Comment by Shougo** [comment]
修正を行いました。確認してください。

**Comment by estrategoreal** [comment]
修正されていることを確認しました。
ありがとうございました。

**Comment by estrategoreal** [comment]
VimFilerExplorer のウィンドウが gvim を実行したディレクトリではなく、常に $HOME になってしまします。

**Comment by Shougo** [comment]
@estrategoreal 再現しません。別 issue に最小構成 .vimrc を作って報告してください。
