### ISSUE TITLE
Always open with VimFilerExplorer in $HOME directory

### ISSUE THREAD

**Issue by estrategoreal** [Shougo/vimfiler.vim#287]
$HOME 以外のディレクトリに移動後、vim 起動時のオプションを下記の通り指定して実行すると、VimFilerExplorer の表示ディレクトリが、カレントではなく $HOME になる。

1901168 以前は vim が実行されたディレクトリで VimFilerExplorer が起動していた。
-buffer-name=explorer のオプションを指定しない場合、1901168 を境に逆の症状になる。

```
$ vim +"VimFiler -buffer-name=explorer ~" +tabnew +"VimFilerExplorer"
```

.vimrc
```
set nocompatible

set runtimepath+=~/.vim/bundle/unite.vim
set runtimepath+=~/.vim/bundle/vimfiler.vim

filetype plugin indent on

**Comment by Shougo** [comment]
原因が分かりました。仕様です。なぜなら、`"VimFiler -buffer-name=explorer ~"`で作成したバッファに
`"VimFilerExplorer"`でジャンプしているからです。既存の vimfiler にジャンプするとき引数がない場合、現在のカレントディレクトリを引き継ぎます。

`VimFilerCurrentDir -explorer` を使用してください。

**Comment by estrategoreal** [comment]
なるほど。
目的とすることが出来ました。
マニアックな使い方していてすみません。IDE っぽく起動して使っているもので。

いつも素早い対応ありがとうございます。
大変助かりました。
