### ISSUE TITLE
Overwritten the specified directory

### ISSUE THREAD

**Issue by estrategoreal** [Shougo/vimfiler.vim#288]
$HOME 以外のディレクトリで下記コマンドを実行すると、どちらのタブも current directory で表示される。
また使い方の問題でしょうか。

```
vim +"VimFiler ~" +tabnew +"VimFilerCurrentDir"
```
.vimrc
```
set nocompatible

set runtimepath+=~/.vim/bundle/unite.vim
set runtimepath+=~/.vim/bundle/vimfiler.vim

filetype plugin indent on

**Comment by Shougo** [comment]
> $HOME 以外のディレクトリで下記コマンドを実行すると、どちらのタブも current directory で表示される。
また使い方の問題でしょうか。

おそらくそうです。タブが違うとはいえ、同じバッファを共用されてしまっています。
別々に扱いたいときは、`-create` を使ってください。

```
vim +"VimFiler ~" +tabnew +"VimFilerCurrentDir -create"
```

が正しいです。

**Comment by estrategoreal** [comment]
ありがとうございます。
望み通りのことが出来ました。

ヘルプ見ろって話ですね。失礼しました。(^^;
