### ISSUE TITLE
Switch to test folder and back

### ISSUE THREAD

**Issue by trungphan** [Shougo/vimfiler.vim#289]
Is there a way to switch to corresponding test folder (back and forth)? For example, suppose I have these folders:
src/java/main/com/example
src/test/main/com/example

I want to easily switch between these two folders.

**Comment by Shougo** [comment]
You should use `<Plug>(vimfiler_switch_to_history_directory)`.

**Comment by trungphan** [comment]
Not sure how history can do anything here because there is no history to start with. Suppose that I'm in folder src/java/main/a/b/c/d/e/f/g/ and want to switch to src/test/main/a/b/c/d/e/f/g/ and there is no history, how can I do that?

**Comment by Shougo** [comment]
You can change `g:vimfiler_detect_drives` value and use `<Plug>(vimfiler_switch_to_drive)`.

**Comment by trungphan** [comment]
It's not exactly what I need. That's OK, I do a little scripting for my own vimrc. In a nutshell, it's something like this:
call vimfiler#mappings#cd(substitute(vimfiler#get_current_vimfiler().current_dir, "src/java/main", "src/test/main", ""))

But I have to make it a bit more flexible to switch between src/java/main/blah/blah/blah/ and src/test/main/blah/blah/blah/

**Comment by Shougo** [comment]
You can add the directory in the bookmark using `:UniteBookmarkAdd`.
You can jump to the directory by `:VimFiler bookmark:`.
