### ISSUE TITLE
Unexpectedly 'winfixwidth' is specified to a buffer which opened by 'E' from VimFilerExplorer

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/vimfiler.vim#290]
**Minimum vimrc**
```vim
" vim -u ~/vimrc.min
set nocompatible
set runtimepath&
 
let s:required_plugins = [
      \ expand('~/.vim/bundle/unite.vim'),
      \ expand('~/.vim/bundle/vimfiler.vim'),
      \]
for s:required_plugin in s:required_plugins
  execute printf('set runtimepath+=%s', s:required_plugin)
endfor
```

**Procedure**
1. `vim -u ~/vimrc.min`
2. `:VimFilerExplorer` (Note: `:VimFiler` works fine)
3. Press `E` to open two files
4. (optional) Change a window size of the opened buffer with `<C-w>>`
5. Press `<C-w>=` **does not work (nothing happen)**

**Expect**
`winfixwidth` of `:VimFilerExplorer` might cause this issue?
I'm not really sure if it is a bug or an expected behaviour.

**Comment by lambdalisue** [comment]
I found that a value of `&winfixwidth' of the opened buffer is `1` when the buffer was opened by `E` from `VimFilerExplorer`. vimfiler should not set `winfixwidth` of the opened buffer right?

**Comment by lambdalisue** [comment]
Probably this. https://github.com/lambdalisue/vimfiler.vim/blob/master/autoload/vimfiler/handler.vim#L173

**Comment by lambdalisue** [comment]
Monkey-patch. In case someone face same problem.

```vim
function! s:vimfiler_settings()
  " Monkey-patch of Issue 290
  nmap <buffer> E <Plug>(vimfiler_split_edit_file):set nowinfixwidth<CR>
endfunction
autocmd MyAutoCmd FileType vimfiler call s:vimfiler_settings()
```

**Comment by Shougo** [comment]
It is feature.
Please see below https://github.com/Shougo/vimfiler.vim/pull/14.

**Comment by lambdalisue** [comment]
Monkey-patch 版のが明らかに理想とする動きだと思ったのでPRしました
