### ISSUE TITLE
Explorer color problem

### ISSUE THREAD

**Issue by yusiwen** [Shougo/vimfiler.vim#293]
![default](https://cloud.githubusercontent.com/assets/3704932/8223966/bdf4a1ee-15b1-11e5-82ab-483187756d3d.png)

Thanks a lot for your great job! I've recently switched from NERDTree to vimfile.vim, and I found that in the explorer, the trailing space of each line is red, don't know what cause it and how to change it.

Ubuntu:15.04 x64
vim: vim-gtk, 7.4.488
color-theme: gruvbox

Regards

**Comment by Shougo** [comment]
Unfortunatelly, vimfiler does not add the color.
You should check your .vimrc.

**Comment by yusiwen** [comment]
Thanks. 

I've finally found what cause this problem. There is a plugin called 'vim-better-whitespace' which highlights the trailing whitespaces of every line in a buffer. How can I trail the whitespace of every line in explorer?

**Comment by Shougo** [comment]
You should disable the plugin in vimfiler buffer.
