### ISSUE TITLE
Is there a way to use custom source from Unite in vimfiler?

### ISSUE THREAD

**Issue by ryanoasis** [Shougo/vimfiler.vim#294]
I am trying to add icons per filetype, I have done this on **Unite** but reading through the docs on Unite and **vimfiler.vim** I have become pretty confused how to continue.

This is what I have for unite:

```vim
let s:filters = {
\   "name" : "my_converter",
\}

function! s:filters.filter(candidates, context)
    for candidate in a:candidates
        let bufname = bufname(candidate.action__buffer_nr)
        let filename = fnamemodify(bufname, ':p:t')
        let path = fnamemodify(bufname, ':p:h')
        let icon = WebDevIconsGetFileTypeSymbol(filename)

        " Customize output format.
        let candidate.abbr = printf("%s %s %s", icon, filename, path)
    endfor
    return a:candidates
endfunction

call unite#define_filter(s:filters)
unlet s:filters


call unite#custom#source('buffer', 'converters', 'my_converter')
```

in case it matters or you are curious this is for https://github.com/ryanoasis/vim-webdevicons/issues/54

Thanks to anyone who reads this!

**Comment by Shougo** [comment]
If you want to add icons, you should create new columns.

**Comment by ryanoasis** [comment]
@Shougo Okay thanks. I will give that a try.

**Comment by ryanoasis** [comment]
@Shougo Awesome I have figured out how to create a custom column.
There was nothing in the docs but it was pretty easy to follow the already created code :+1:  :tada:
