### ISSUE TITLE
vimfiler split problem

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#295]
Consider the following minimal vimrc

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimfiler

call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 20,
            \ })
```

As in the GIF, open Gvim and run `:VimFiler`, select a file and press `<CR>` to open it. The file will open on the same narrow window of the original Vimfiler buffer. I expect it to open occupying the whole window.

![vimfiler](https://cloud.githubusercontent.com/assets/2583971/8293057/7069243a-1909-11e5-9f83-cef35f3b9c63.gif)

**Comment by Shougo** [comment]
It is feature.  If you want to edit it in another window, you should use explorer mode.

```vim
:VimFiler -explorer
```

**Comment by petobens** [comment]
Thanks for the quick reply. However I still get the same behavior when using the following minimal vimrc (which sets `explorer` as a default):

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

if has('vim_starting')
    execute 'set runtimepath+=' . expand('$DOTVIM/bundle/neobundle')
endif
call neobundle#begin(expand('$DOTVIM/bundle/'))
let g:neobundle#enable_name_conversion = 1
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler', {'lazy' : 1, 'autoload' : {
        \ 'commands' : ['VimFilerBufferDir', 'VimFiler',
        \ 'VimFilerCreate', 'VimFilerTab'],
        \ 'explorer' : 1
        \ }
        \ }
call neobundle#end()

call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ })
```

**Comment by Shougo** [comment]
No.

```vim

call vimfiler#custom#profile('default', 'context', {
            \ 'explorer': 1,
            \ 'winwidth' : 40,
            \ })
```

is correct.

**Comment by petobens** [comment]
I don't get it. If I use 

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimfiler

call vimfiler#custom#profile('default', 'context', {
            \ 'explorer' : 1,
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ })
```
I still get the problem:

![vimfiler](https://cloud.githubusercontent.com/assets/2583971/8310483/a36f3d5e-19a6-11e5-968f-05202cc65448.gif)

I think the problem is somehow related to  the `split` option.

**Comment by Shougo** [comment]
OK.  I will check the behavior.

**Comment by Shougo** [comment]
```vim
call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ 'no_quit': 1,
            \ })
```

**Comment by petobens** [comment]
Thank @Shougo  but I want to quit the vimfiler buffer once the file opens.

**Comment by petobens** [comment]
I think the problem was introduced in this commit  b1d7cfca897dff12933020f5494b6ae5e5e1d629

**Comment by Shougo** [comment]
> Thank @Shougo but I want to quit the vimfiler buffer once the file opens. 

I don't want to implement the feature.

**Comment by petobens** [comment]
@Shougo what I mean is that the behavior has recently changed (it is not a new feature). With the following minimal vimrc (latest vimfiler version):

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

if has('vim_starting')
    execute 'set runtimepath+=' . expand('$DOTVIM/bundle/neobundle')
endif
call neobundle#begin(expand('$DOTVIM/bundle/'))
let g:neobundle#enable_name_conversion = 1
NeoBundleFetch 'Shougo/neobundle.vim', {'name' : 'neobundle'}
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler', {'lazy' : 1, 'autoload' : {
        \ 'explorer' : 1 } }
" NeoBundle 'Shougo/vimfiler', {'lazy' : 1, 'rev' : '78e51d0', 'autoload' : {
        " \ 'explorer' : 1 } }
call neobundle#end()

call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'force_quit' : 1,
            \ 'winwidth' : 40,
            \ })
```

When I try to open a file, it opens in the same vimfiler window:

![vimfiler1](https://cloud.githubusercontent.com/assets/2583971/8385592/c018ead8-1c1f-11e5-9dcb-618cc85dc2dd.gif)

If I use the previous vimfiler version:

```vim
NeoBundle 'Shougo/vimfiler', {'lazy' : 1, 'rev' : '78e51d0', 'autoload' : {
        \ 'explorer' : 1 } }
```
then the vimfiler windows is closed and the file correctly opens on a (new) window:

![vimfiler2](https://cloud.githubusercontent.com/assets/2583971/8385613/de980084-1c1f-11e5-8e49-9c96d346e5bc.gif)

I think this is the correct behavior. Please fix it (for instance reverting the change).

**Comment by Shougo** [comment]
> @Shougo what I mean is that the behavior has recently changed (it is not a new feature). With the following minimal vimrc (latest vimfiler version):

Because, the previous behavior is wrong/inintended.
Please see https://github.com/Shougo/vimfiler.vim/issues/292.

**Comment by Shougo** [comment]
```vim
call vimfiler#custom#profile('default', 'context', {
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ 'force_quit': 1,
            \ })
```

**Comment by petobens** [comment]
Thank you!
