### ISSUE TITLE
Cancel file opening with vim-choosewin

### ISSUE THREAD

**Issue by p0deje** [Shougo/vimfiler.vim#299]
I'm using vimfiler and vim-choosewin which play really nicely. However, there is a single issue that it's not possible to cancel file opening. For example, when I hit `o` on file in vimfiler explorer, choosewin overlay is shown to allow choose window for file open. But if I want to cancel operation and hit `Esc`, file is still opened in the last window in use.

I suppose it should be possible to cancel file open operation at choose window stage.

**Comment by Shougo** [comment]
Unfortunatelly, it is not possible.
You cannot cancel the open.

**Comment by p0deje** [comment]
Ok, thanks for letting me know.



Cheers,Alex
