### ISSUE TITLE
Copy relative path only

### ISSUE THREAD

**Issue by krzkrzkrz** [Shougo/vimfiler.vim#300]
Vim was opened at ` /Users/foo/Sites/project-dir`.

When doing `yy`. It copies the full path of the file. ie:

    /Users/foo/Sites/project-dir/app/pods/components/popup-modal/component.js

Is it possible to copy only the relative path instead? ie

    /app/pods/components/popup-modal/component.js

**Comment by Shougo** [comment]
No.
