### ISSUE TITLE
Sort numbers in filenames in increasing order

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#301]
Hi @Shougo, is it possible to sort filenames numbers in increasing order? Currently vimfiler sorts them like this:

![screenshot-18-07-2015_12-50-45](https://cloud.githubusercontent.com/assets/2583971/8762309/d5a9ec84-2d4b-11e5-8297-be4ea3864c89.png)

I would like to sort them like:

```
foo.m
foo_1.txt
foo_2.txt
foo_11.txt
```

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!!
