### ISSUE TITLE
Background after tree is not pretty in my colorscheme

### ISSUE THREAD

**Issue by oblitum** [Shougo/vimfiler.vim#302]
I use a plugin that highlights any whitespace after the last non-whitespace character in the line, the problem is that vimfiler seems to fill the file tree with whitespace after file names so it ends up like this for me:

![screen shot 2015-07-21 at 23 22 17](https://cloud.githubusercontent.com/assets/1269815/8816631/04472c3a-3000-11e5-9df7-0dc46609c17c.png)

It would be best if it was possible for it not to rely on ending whitespace. Is it possible?

**Comment by Shougo** [comment]
It is feature.
You should disable the highlight in vimfiler buffer.

**Comment by oblitum** [comment]
@Shougo The whitespace being a feature I'm not sure, but you're right it was easy to fix:

```vim
" better-whitespace Setup {{{
let g:better_whitespace_filetypes_blacklist = ['vimfiler']
" }}}
```

But in truth, this was not the hard one to fix... I have other highlighting, it's one that's enabled for
any text that goes beyond `textwidth`, sadly even if setting `textwidth` to 0 for `vimfiler` buffer, it doesn't
work from .vimrc, solely when doing it by hand.

**Comment by oblitum** [comment]
Hi @Shougo, can you give me a hand here? `let g:better_whitespace_filetypes_blacklist = ['vimfiler']` has been working correctly up until recently, now there's a glitch that seems like a vimfiler issue:

I get whitespace highlighted the first time I open vimfiler, because at the first time I open it, it's not named as "vimfiler" in the bottom, it's something ending with \*safe\*, after I close and open it a second time, the buffer is correctly titled as vimfiler, and hence, the blacklisting works.

**Comment by oblitum** [comment]
Here're before and after pictures, notice the buffer title near the lock icon:

![before](https://cloud.githubusercontent.com/assets/1269815/10372937/c607b2d8-6dc0-11e5-8288-e000a9dc4968.png)

![after](https://cloud.githubusercontent.com/assets/1269815/10372941/cbc6cbe6-6dc0-11e5-8dc9-8afa8cbf8830.png)

**Comment by Shougo** [comment]
@oblitum OK.  I will try it.   Please create minimal .vimrc less than 50 lines.  and upload reproduce ways.

**Comment by oblitum** [comment]
@Shougo, the following `.vimrc` in full, reproduces the same problem:

```viml
" VIM-PLUG Setup {{{

" Automatic installation {{{
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim
          \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    au VimEnter * PlugInstall
endif
" }}}

call plug#begin('~/.vim/plugged')

let mapleader = ' '

" Plugins {{{
Plug 'ntpeters/vim-better-whitespace'
Plug 'Shougo/vimfiler.vim'
Plug 'tpope/vim-sensible'
Plug 'Shougo/unite.vim'
" }}}

call plug#end()

" Plugin Preloading {{{
runtime! plugin/sensible.vim
" }}}

" }}}

" VimFiler Setup {{{
let g:vimfiler_as_default_explorer = 1
nnoremap <leader>f :VimFilerExplorer<cr>
" }}}

" better-whitespace Setup {{{
let g:better_whitespace_filetypes_blacklist = ['vimfiler']
" }}}
```

**Comment by Shougo** [comment]
Confirmed.
It is vim-better-whitespace regression.
Closing.

https://github.com/ntpeters/vim-better-whitespace/issues/34

**Comment by oblitum** [comment]
Thanks @Shougo, this does fix that issue with vim-better-whitespace, sorry to report it here.
