### ISSUE TITLE
Regression: Accessing same-named buffers across tabs

### ISSUE THREAD

**Issue by rafi** [Shougo/vimfiler.vim#305]
Commit 0a38f55f re-introduced the issue in #239 
I enjoy keeping VimFiler's state (expand/collapsed directories) across tabs for the same project.
You've fixed it in bb2d748b but in 0a38f55f it was removed.
Can you return this feature?

Reverting this block:
```viml
" autoload/vimfiler/init.vim:383

            \ && ((context.buffer_name !=# 'default'
            \         && context.buffer_name !=# 'explorer')
            \      || !exists('t:tabpagebuffer')
```
brings back the feature, but then the buffer is not re-initialized in a new tab...

**Comment by Shougo** [comment]
Unfortunatelly, it is feature.
Pull request is wellcome.
If you can fix both #239 and #286.

**Comment by rafi** [comment]
Could you explain issue #286 in english ?

**Comment by rafi** [comment]
Maybe open same-name buffers with same state as "parent" tab?
For example, when opening `vimfiler:my-project@1`, it will match the state of opened/closed directories from `vimfiler:my-project` buffer, something like the `-find` option.
