### ISSUE TITLE
Combine smart_h and switch_to_parent_directory

### ISSUE THREAD

**Issue by rosshadden** [Shougo/vimfiler.vim#307]
Instead of having two separate binds for collapsing and changing to parent directory, have you considered making `vimfiler_smart_h` do both?  That is, if `vimfiler_smart_h` is run when there are no collapsed directories, change to the parent directory.

This change would not change any existing functionality, it would merely add an additional use of `vimfiler_smart_h`, which currently does nothing in the above scenario.  Also, this behavior would be consistent with how [`vifm`](http://vifm.info/) works, where `h` and `l` navigate through directory hierarchies.

If this is not a desired change, is there a way I can do it in my own config?  Is there perhaps a variable that would tell me if the selected folder is either collapsed or is a file?

**Comment by Shougo** [comment]
OK.  I will consider it.

**Comment by rosshadden** [comment]
Thanks @Shougo!
