### ISSUE TITLE
Git status

### ISSUE THREAD

**Issue by rosshadden** [Shougo/vimfiler.vim#308]
Is it possible within the current implementation for `vimfiler` to have git status icons next to files/folders?  There was [a plugin for NERDTree](https://github.com/Xuyuanp/nerdtree-git-plugin) that did this, and I would like to achieve similar behavior in `vimfiler`.

I'm not asking if it's "easy" or if there are already existing options to do so---I know this is not the case.  I just want to know if there is a way I could make it work, either in my config or by forking the plugin.

Thanks!

**Comment by Shougo** [comment]
It should be implemented vimfiler's column feature.
So, you can create it.
I don't want to add the feature though.

**Comment by rosshadden** [comment]
Awesome, thank you.

**Comment by tomauty** [comment]
Sorry for bumping a closed thread. When you say you don't want to add the feature, do you mean you won't accept a PR with optional git status support? Or just that you don't feel like doing it :)

**Comment by Shougo** [comment]
If you send the PR, I will check it.
