### ISSUE TITLE
Hide VimFilerExplorer and resume from last position

### ISSUE THREAD

**Issue by frace** [Shougo/vimfiler.vim#310]
Most of the time I do use `VimFilerExplorer -force-quit` to navigate the filesystem.

After opening a file I think it would be useful to hide the buffer in favor of closing it in order to resume from the last position in the filesystem. Right now `-force-quit` really quits `VimFileExplorer`. An option like `-resume` would be really nice.

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Hi @Shougo  and @frace , I think that the `--force-quit` flag should really quit the Vimfiler buffer rather than close it. Is it possible to revert this change? (and maybe add a resume flag or something similar to address @frace request)

**Comment by Shougo** [comment]
@frace  @petobens Added -force-hide option

**Comment by petobens** [comment]
Thank you @Shougo

**Comment by rafi** [comment]
This is great, thanks!!

**Comment by frace** [comment]
Thank you very much @Shougo!
