### ISSUE TITLE
Respect project ignore files (.gitignore, etc.)

### ISSUE THREAD

**Issue by rosshadden** [Shougo/vimfiler.vim#311]
Is there a way to have `vimfiler` not show items matched by project ignore files?  For example, `.gitignore`.

In `unite.vim` this is commonly done by setting the commands to be `ag` or `ack` instead of `grep`.  I couldn't find in the docs a way to customize the directory-listing command used, but if this were exposed I could solve my issue by using `ag --depth=0 -g .` or something instead of `ls`.

**Comment by Shougo** [comment]
It seems good feature.
But current ignore files feature is too simple.
To implement it, vimfiler matcher feature is needed.

**Comment by rosshadden** [comment]
I think ideally such a feature would function as the existing `<Plug>(vimfiler_toggle_visible_ignore_files)` and `<Plug>(vimfiler_toggle_visible_dot_files)` do, where they may be toggled at will.

**Comment by Shougo** [comment]
Of course.

**Comment by Shougo** [comment]
Implemented.  Please update unite.vim and vimfiler.

**Comment by rosshadden** [comment]
Thank you @Shougo.  It is working, and (just like you warned in your docs) slow for big projects.  Is this toggleable on the fly?  That is, can we bind a key in the `vimfiler` buffer to change the ignore_filters for that buffer?

**Comment by Shougo** [comment]
>  Is this toggleable on the fly?

`<Plug>(vimfiler_toggle_visible_ignore_files)`
