### ISSUE TITLE
error occurred when closing vimfiler with '-split -simple -no-quit' option

### ISSUE THREAD

**Issue by e-mon** [Shougo/vimfiler.vim#312]
以下の手順でエラーが発生します．

* 1. `:VimFilerBufferDir -split -simple -no-quit`
* 2. 適当なファイルを開く
* 3. `:VimFilerBufferDir -split -simple -no-quit`
* 6. `q`で閉じる

vimrc:
```vim
set nocompatible
filetype off
set rtp+=/path/to/vimfiler
set rtp+=/path/to/unite
filetype plugin on
syntax enable
```

error message:
function vimfiler#util#hide_buffer の処理中にエラーが検出されました:
行   14:
E16: 無効な範囲です: 2wincmd w

確認したところ，手順1の初回vimfiler起動時に保存された`context.vimfiler__prev_winnr`はvimfilerを起動していない状態での番号ですが，もう一度手順3にて起動する際にvimfilerを含めたウィンドウ番号に更新されるため下記部分で無向な範囲となるようです．

https://github.com/Shougo/vimfiler.vim/blob/master/autoload/vimfiler/util.vim#L183-L184
よろしくお願いします．

**Comment by Shougo** [comment]
原因解明ありがとうございます。修正しました。
