### ISSUE TITLE
VimFilerCreate as an option

### ISSUE THREAD

**Issue by tex** [Shougo/vimfiler.vim#313]
Hi,

I want to create a new VimFiler buffer with VimFilerBufferDir and not to reuse existing VimFiler buffer.
Can you add option to specify not to reuse existing VimFiler buffer? Like a combination of VimFilerBufferDir and VimFilerCreate?

Thanks!

BTW: Perfect plugin, using it daily.

**Comment by Shougo** [comment]
`:VimFiler -create`
Please read the documentation.

**Comment by tex** [comment]
Thanks! And sorry that I missed this option, it does exactly what I want.
