### ISSUE TITLE
When set updatetime=100, cannot loop cursor up from the top down to the bottom

### ISSUE THREAD

**Issue by phphong** [Shougo/vimfiler.vim#314]
When I `set updatetime=100` (or a smaller number, mainly to use with vim-gitgutter) then whenever I move the cursor up to the first line (the `..` line), then immediately it's jumped back to the second line (which contains the first child in the current directory). Because of this, I cannot loop down to the bottom unless I hold the `k` key to go up continuously. After some research, I found out that it's because of these:
In `vimfiler.vim/autoload/vimfiler/view.vim`, line `166` to `168`:

    elseif line('.') == 1 && last_line == 1
    " Initialize cursor position.
    call cursor(b:vimfiler.prompt_linenr+1, 0)

If these 3 lines are commented out, everything is fine

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please upload minimal .vimrc and reproduce ways from Vim starting.

**Comment by phphong** [comment]
## Environment
* Ubuntu 14.04
* Vim: 
  * VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 14 2015 17:54:59)
  * Included patches: 1-826
* Terminal: Konsole

## Minimal `vimrc`:
    set runtimepath+=~/.vim/plugged/vimfiler.vim
    set runtimepath+=~/.vim/plugged/unite.vim
    set updatetime=100
    nnoremap <silent> <F1> :VimFilerCurrentDir -split -simple -winwidth=35 -toggle -no-quit<cr>

## How to reproduce:
1. Enter a non-empty directory
2. Press `F1` to open Vimfiler window
3. Inside Vimfiler window, press `k` repeatedly to go up. **Problem**: cursor cannot loop down to the bottom

**Comment by Shougo** [comment]
Fixed.
