### ISSUE TITLE
Wrong display and infinite loop when opening an empty folder

### ISSUE THREAD

**Issue by AlexMasterov** [Shougo/vimfiler.vim#316]
# Problems summary
Wrong display and infinite loop when opening an empty folder.

## Environment Information
 * OS: Windows 10
 * Vim version: 7.4.865

## Reproducable ways from Vim starting
1. Minimal vimrc
2. Put any file in the root
3. Create an empty folder
4. Try to open the empty folder

## Screenshots
![1](https://cloud.githubusercontent.com/assets/700213/9822653/420fef3c-58ca-11e5-92e5-4003dd70d66a.png)
![2](https://cloud.githubusercontent.com/assets/700213/9822654/42124c32-58ca-11e5-8d8e-6673751283bb.png)
![3](https://cloud.githubusercontent.com/assets/700213/9822655/4212e020-58ca-11e5-9c51-1e5eb0eb2b5e.png)

**Comment by Shougo** [comment]
Reproduced.  It is fatal vimproc problem.

https://github.com/Shougo/vimproc.vim/issues/209

**Comment by AlexMasterov** [comment]
Updated vimproc.
Now everything works as it should. Thank you.

**Comment by Shougo** [comment]
OK.
