### ISSUE TITLE
Open new file after creating it 

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#317]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimfiler

filetype plugin indent on

call vimfiler#custom#profile('default', 'context', {
            \ 'force_quit': 1,
            \ 'safe': 0
            \ })
```
i) Open Gvim
ii) run `:VimFiler`
iii) Create a new file with the `N` mapping; name it `foo.txt`

Once the file is created the vimfiler buffer exits but it doesn't open the `foo.txt` file. Once the file is created and the buffer exits I expect it to open the newly created file.

![blahh](https://cloud.githubusercontent.com/assets/2583971/9978443/3ef68928-5f05-11e5-9d32-360dd6cd6fa4.gif)

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/1005

It is feature.
I think you should use `<Plug>(vimfiler_new_file)<Plug>(vimfiler_edit_file)` mapping.

**Comment by petobens** [comment]
@Shougo, I'm probably doing something wrong. When I write

```vim
nmap <buffer> F <Plug>(vimfiler_new_file)<Plug>(vimfiler_edit_file)
```

and press `F`, the command line looks like this:

![screenshot-22-09-2015_22-49-03](https://cloud.githubusercontent.com/assets/2583971/10036306/275edcba-617c-11e5-9af6-d129802c0b6e.png)

How should I write the mapping?

**Comment by Shougo** [comment]
Sorry, fixed.  You don't have to map it.
You can press `<Plug>(vimfiler_edit_file)` mapping though.

**Comment by petobens** [comment]
Thanks for the quick fix but it is still not working for me:
With my minimal vimrc:

i) Open Gvim
ii) Press `N`
iii) Create file `foo.txt`
iv) I have to press `<CR>` to open `foo.txt`

I don't want to do step iv). What I want is that once the file is created it automatically opens it for editing:

![gif](https://cloud.githubusercontent.com/assets/2583971/10036603/273dc0e4-6180-11e5-883a-590d7850c7df.gif)

I tried again with the mapping:

```vim
nmap <buffer> F <Plug>(vimfiler_new_file)<Plug>(vimfiler_edit_file)
```

but I get the same behavior as in my screenshot above.

**Comment by Shougo** [comment]
Unfortunately, it is feature.

**Comment by petobens** [comment]
Ok. But can I somehow write a mapping to fix the behaviour?

**Comment by Shougo** [comment]
I think nothing...
Because, `<Plug>(vimfiler_newfile)` needs user input.

**Comment by petobens** [comment]
Mmmm what a pity. I really liked the old behavior.

**Comment by Shougo** [comment]
I like current behavior.
Because, in the old behavior you cannot do other file actions.

**Comment by petobens** [comment]
Ok, I understand. Thanks anyways.
