### ISSUE TITLE
E492: Not an editor command: VimFiler

### ISSUE THREAD

**Issue by wolfv6** [Shougo/vimfiler.vim#319]
I installed Unite on Vim 7.4 via Vundle.
The Unit command lists the current directory:

    :Unite file

But the VimFiler command gets an error:

    :let g:vimfiler_as_default_explorer = 1
    :VimFiler
    E492: Not an editor command: VimFiler

How to install and run VimFiler?

Thank you.

**Comment by dimitriye98** [comment]
You need to install VimFiler as well with the line:
`Plugin 'Shougo/vimfiler.vim'`
in your `.vimrc`

**Comment by Shougo** [comment]
Yes, unite.vim is not vimfiler.
vimfiler is not installed by default.

**Comment by wolfv6** [comment]
Thanks dimitriye98 and Shougo.
VimFiler works great.
