### ISSUE TITLE
New files not opening

### ISSUE THREAD

**Issue by daveyarwood** [Shougo/vimfiler.vim#321]
Hello,

I'm not sure if this is a vimfiler-specific problem, or if there is something else going on, but maybe you can help me figure it out.

I was using vimfiler for quite a while with no problems. One thing I would do a lot is create a new file with `N`, then Enter through to open the blank file and start editing.

For some reason (possibly after updating my plugins?), vimfiler has stopped opening a new file when I enter through. Now after I type `N` and create the new file, then press Enter, it just closes the vimfiler window. I can then open the file by re-opening vimfiler, navigating to the new file and pressing Enter.

Any ideas?

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/317

**Comment by daveyarwood** [comment]
It's fixed for me after updating vimfiler. Thanks!
