### ISSUE TITLE
repertory vimfiler not found in the cdpath

### ISSUE THREAD

**Issue by codeur4** [Shougo/vimfiler.vim#322]
I am on a windows 7 64 bit and vim 64bit version.
With `:VimFiler` I get the error (repertory "C:\Users\herve\vimfiler" not found in the cdpath) :
![vimfiler_cdpath](https://cloud.githubusercontent.com/assets/10487632/10124674/e1e2286c-655a-11e5-8039-0e5f77a78e84.jpg)
It works fine if I create this repertory (vimfiler)
The problem is that I change to directory of current file automatically in order to use Unite properly :
`autocmd BufEnter * lcd %:p:h "change to directory of current file automatically`
So I can't create this vimfiler reportory everywhere ..
Any idee ?

**Comment by Shougo** [comment]
You should not use the config.
It breaks vimfiler behavior.

**Comment by codeur4** [comment]
When I remove `autocmd BufEnter * lcd %:p:h` it works well ok.
Thanks
