### ISSUE TITLE
Conflict with trailing-whitespace plugins when VimFiler is first called

### ISSUE THREAD

**Issue by tbastos** [Shougo/vimfiler.vim#323]
First, thanks for all the great plugins :)

The problem I found only happens the first time I call `:VimFiler -simple` after opening vim.

My trailing-whitespace plugins highlight the trailing spaces in the `:VimFiler -simple` buffer, despite being set to ignore filetypes 'unite' and 'vimfiler'. The next time I call `:VimFiler -simple` everything is ok, though.

Since this happens with multiple trailing-whitespace plugins and it does NOT happen in unite buffers, I'm guessing it's a vimfiler-specific problem? Something to do with the order in which the filetype is set?

This is just slightly annoying, but I would love to find a solution :D

Thanks!

**Comment by Shougo** [comment]
It is not vimfiler problem.
Just the whitespace plugin's failure.
The whitespace plugin should be ignored nofile buffers.
