### ISSUE TITLE
vimfiler extension

### ISSUE THREAD

**Issue by romgrk** [Shougo/vimfiler.vim#324]
Hello,

This is not an issue.

I wrote a vimfiler extension some time ago, and I tought it would be nice to share it in case anyone would like to use it. Here is the code: https://github.com/romgrk/vimfiler-prompt
Feel free to include a link or not (I can't guarantee it'll work in all cases; it's not much tested).

Oh, and also I was wondering, are you open to PR on this repository?

In any case, thanks for the good work!

**Comment by Shougo** [comment]
Oh, thanks.  It seems good extension.

> Feel free to include a link or not (I can't guarantee it'll work in all cases; it's not much tested).

I can include the link.

> Oh, and also I was wondering, are you open to PR on this repository?

What do you mean?
To include the extension in vimfiler?

**Comment by romgrk** [comment]
No, actually it's about the highlighting & syntax, and the icons.
I had various changes in mind, that would require minor implementation changes 
e.g. marking files with different HL, without changing the icon
e.g. displaying different icons for each filetype
e.g. highlighting difference from git-index

Let me know how you feel about this, otherwise I can always override my local version of vimfiler. I don't have anything started yet, and in any case I'll check with you before starting implementing anything specific.

**Comment by Shougo** [comment]
OK.  Please create different PRs.

**Comment by Shougo** [comment]
I added the extension section.  Closing.
