### ISSUE TITLE
Updated to latest getting errors

### ISSUE THREAD

**Issue by dshills** [Shougo/vimfiler.vim#325]
I am at commit feaa54e08a62720e5213874849b67fff519a43f4

I have attached a screenshot of the errors. I have insured the unite plugin is at the latest as well as vimproc

<img width="880" alt="screen shot 2015-10-03 at 6 12 29 pm" src="https://cloud.githubusercontent.com/assets/5123546/10265556/7136b340-69fa-11e5-8d2e-af3808b5fa46.png">

**Comment by Shougo** [comment]
I cannot reproduce the problem.
It seems vimfiler or unite regexp regression.
Please upload minimal .vimrc less than 50 lines.

**Comment by dshills** [comment]
Took me a while but it turned out to be an error in the syntax for vimfiler_ignore_pattern. Sorry for the confusion

**Comment by Shougo** [comment]
OK.
