### ISSUE TITLE
Long lines in :VimFiler

### ISSUE THREAD

**Issue by felixSchl** [Shougo/vimfiler.vim#326]
Vim has an issue with syntax highlighting on long lines, refer:
* http://stackoverflow.com/questions/901313/editing-xml-files-with-long-lines-is-really-slow-in-vim-what-can-i-do-to-fix-th
* http://stackoverflow.com/questions/26815604/vim-syntax-performance-with-very-long-lines
* http://superuser.com/questions/302186/vim-scrolls-very-slow-when-a-line-is-too-long
* https://github.com/vim/vim/issues/274

Using `:VimFiler` causes to use the entire buffer and that could be the whole screen, resulting in very long lines, which in turn cripples vim.

I know this is not an issue with your plugin, it runs fine if I `:set synaxcol=1` or similar. So, seeing that this problem is still not fixed in vim, would you consider offering a workaround? Such as artificially narrowing the information?

I saw the `-winwidth` option, but it appears to only take effect on the explorer?

**Comment by Shougo** [comment]
> I saw the -winwidth option, but it appears to only take effect on the explorer?

I added -fnamewidth option for it.

**Comment by felixSchl** [comment]
Awesome! :+1:
