### ISSUE TITLE
Is there a VimFiler tutorial?

### ISSUE THREAD

**Issue by wolfv6** [Shougo/vimfiler.vim#327]
Is there a VimFiler tutorial? I don't know enough VimFiler to understand the documentation.

In VimFiler, what is the text between the file name and the date? e.g.

    fileName1          7B 15/08/18
    fileName2         10B 15/08/16

"Common operations" on https://github.com/Shougo/vimfiler.vim README.md
shows "New directory names (comma separated): test" on bottom of window.
How to enter that in my gvim window?

A question about https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt

    What does <Plug> mean? e.g.

    <Plug>(vimfiler_make_directory)     *<Plug>(vimfiler_make_directory)*
     Creates new directory. If directory tree is opened, will
     create new directory in directory tree.
     If you marked files, will move the files in new directory.
     Note: This mappings is disabled in vimfiler safe mode.

**Comment by Shougo** [comment]
> Is there a VimFiler tutorial? I don't know enough VimFiler to understand the documentation.

Nothing.  You can create it.

> In VimFiler, what is the text between the file name and the date? e.g.

It is the file size.

> "Common operations" on https://github.com/Shougo/vimfiler.vim README.md
shows "New directory names (comma separated): test" on bottom of window.
How to enter that in my gvim window?

You can use K key.  You should read `:help vimfiler-default-keymappings`.

> What does `<Plug>` mean? e.g.

`:help <Plug>`
