### ISSUE TITLE
vimfiler doesn't work

### ISSUE THREAD

**Issue by lucerion** [Shougo/vimfiler.vim#328]
After opening vimfiler shown only `..` No errors. Unite plugin installed.

**Comment by lucerion** [comment]
I found a reason: if I set `let g:vimfiler_ignore_pattern` as `''` (without spaces) it doesn't work, with `'  '`  -  it works. Anyway I don't change this option in config long time and it broken after plugin update. I hope it can help someone else.

**Comment by Shougo** [comment]
Thank you.  Fixed.

**Comment by lucerion** [comment]
Thank you, Shougo for your work and that awesome plugin!
