### ISSUE TITLE
I want to modify value into $srcs and $dest.

### ISSUE THREAD

**Issue by Katsujp** [Shougo/vimfiler.vim#329]
Before there call external copy command with g:unite_kind_file_copy_file_command, I want to replace some characters such as "/" before call external application.

Can I modify values into $srcs and $dest before call external command?

**Comment by Shougo** [comment]
Unfortunately, I cannot understand what you want to do.
Please explain it more clearly.

**Comment by Katsujp** [comment]
Sorry for my cheap request.

When I perform Vimfiler on Windows, I want to use FastCopy.exe (http://ipmsg.org/tools/fastcopy.html). Because it's too faster than cp.exe.

However, FastCopy.exe do not understand path separator "/". So I want to replace to "\" from "/" when Vimfiler performs copy and move commands.

**Comment by Shougo** [comment]
OK.  I get it.
But I reject it.  It seems FastCopy's problem.
And it is not useful for other users.

**Comment by Katsujp** [comment]
Thanks for your comment.
I understood it. I am going to fix it with another way.

I really appreciate your provided addons. I am taking a step away from Afxw.
