### ISSUE TITLE
Problem with :VimFilerExplorer -force-hide

### ISSUE THREAD

**Issue by tbastos** [Shougo/vimfiler.vim#330]
I want VimFilerExplorer to auto-hide after firing an action, and `-force-hide` does this, but for some reason it's also setting WinFixWidth on my first (adjacent) split, so when VimFilerExplorer closes, my layout is messed up. And if I call `:VimFilerExplorer -force-hide` again, it keeps on growing the width of my first split. I have to manually `:set nowfw` and `CTRL+W =` to fix things.

Is this a bug? Otherwise is there a way to auto-hide VimFilerExplorer after firing an action?

Thanks!

**Comment by Shougo** [comment]
Please create minimal .vimrc less than 50 lines and the reproduce ways from Vim starting.

**Comment by tbastos** [comment]
Ok, I reproduced many times with this .vimrc:

``` vim
if has('vim_starting')
  if &compatible
    set nocompatible
  endif
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle (required)
NeoBundleFetch 'Shougo/neobundle.vim'

" Use vimproc for async command execution
NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'windows' : 'tools\\update-dll-mingw',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'linux' : 'make',
      \     'unix' : 'gmake',
      \    },
      \ }
"}}}

NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler.vim'
NeoBundle 't9md/vim-choosewin' " visual window selection

call neobundle#end()
filetype plugin indent on
NeoBundleCheck

nnoremap <silent> <F1> :VimFilerExplorer -force-quit<CR>
nnoremap <silent> <F2> :VimFilerExplorer -force-hide<CR>
```

Steps to reproduce:
1. Create two vertical splits (`:vs`)
2. Use F1 to open any file in split A
3. Use F1 to open another file in split B

When VimFilerExplorer closes after step 3, the splits will not have the same width. If you press F1 and q repeatedly, split A will grow, and its `WinFixWidth=1`

Now, if instead of F1 you use F2 (`-force-hide`) something different happens: after step 2, VimFilerExplorer closes one of the splits. That is, you lose one split, instead of having problems with `WinFixWidth`.

Can you reproduce? Thanks

**Comment by Shougo** [comment]
Fixed.
