### ISSUE TITLE
Restore previous view properly

### ISSUE THREAD

**Issue by WscriChy** [Shougo/vimfiler.vim#331]
The same problem like with unite at [this issue](https://github.com/Shougo/unite.vim/issues/1049).
Fixed by 

    Subject: [PATCH] Fix previous view after VimFiler with '-no-split' option
     quits

    ---
     autoload/vimfiler/init.vim      | 9 ++++++---
     autoload/vimfiler/util.vim      | 1 +
     autoload/vimfiler/variables.vim | 1 +
     3 files changed, 8 insertions(+), 3 deletions(-)

    diff --git a/autoload/vimfiler/init.vim b/autoload/vimfiler/init.vim
    index fd2aa3a..d9699e3 100644
    --- a/autoload/vimfiler/init.vim
    +++ b/autoload/vimfiler/init.vim
    @@ -433,13 +433,15 @@ function! vimfiler#init#_switch_vimfiler(bufnr, context, directory) "{{{
       let search_path = fnamemodify(bufname('%'), ':p')
     
       let context = vimfiler#initialize_context(a:context)
    -  if !context.tab
    -    let context.alternate_buffer = bufnr('%')
    -  endif
       let context.vimfiler__prev_bufnr = bufnr('%')
       let context.vimfiler__prev_winnr = winnr()
     
       if bufwinnr(a:bufnr) < 0
    +    if !context.tab
    +      let context.alternate_buffer = bufnr('%')
    +      let context.prev_win_saved_view = winsaveview()
    +    endif
    +
         if context.split
           execute context.direction
                 \ (context.horizontal ? 'split' : 'vsplit')
    @@ -495,6 +497,7 @@ function! vimfiler#init#_switch_vimfiler(bufnr, context, directory) "{{{
           wincmd p
         else
           execute bufwinnr(a:context.alternate_buffer).'wincmd w'
    +      keepjumps call winrestview(context.prev_win_saved_view)
         endif
       endif
     endfunction"}}}
    diff --git a/autoload/vimfiler/util.vim b/autoload/vimfiler/util.vim
    index 7344bbf..53b89ab 100644
    --- a/autoload/vimfiler/util.vim
    +++ b/autoload/vimfiler/util.vim
    @@ -193,6 +193,7 @@ function! vimfiler#util#alternate_buffer() "{{{
             \ && getbufvar(context.alternate_buffer, '&filetype') !=# 'vimfiler'
             \ && g:vimfiler_restore_alternate_file
         execute 'buffer' context.alternate_buffer
    +    keepjumps call winrestview(context.prev_win_saved_view)
         return
       endif
     
    diff --git a/autoload/vimfiler/variables.vim b/autoload/vimfiler/variables.vim
    index 4304967..e587a5a 100644
    --- a/autoload/vimfiler/variables.vim
    +++ b/autoload/vimfiler/variables.vim
    @@ -97,6 +97,7 @@ function! s:initialize_default_options() "{{{
             \ 'find' : 0,
             \ 'tab' : 0,
             \ 'alternate_buffer' : bufnr('%'),
    +        \ 'prev_win_saved_view' : winsaveview(),
             \ 'focus' : 1,
             \ 'invisible' : 0,
             \ 'columns' : 'type:size:time',
    -- 
    2.1.1

**Comment by Shougo** [comment]
Implemented in https://github.com/Shougo/vimfiler.vim/pull/333.
Please test it.
