### ISSUE TITLE
<Plug>(vimfiler_new_file) show 'choose > ' but the new file won't open.

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/vimfiler.vim#332]
**In short**

While `<Plug>(vimfiler_new_file)` won't open the created file, do you need this line? 
https://github.com/Shougo/vimfiler.vim/blob/master/autoload/vimfiler/mappings.vim#L1551

**Problem**

`<Plug>(vimfiler_new_file)` show 'choose >' step but it won't open the created buffer thus the step is just annoying. And after creation, the focus is on the buffer I choose thus I have to re-focus vimfiler window and have to**select** the newly created file while the cursor is not on the file created.

**Procedure**

1. Open VimFilerExplorer (`:VimFilerExplorer`)
2. Open at least two buffers
3. Hit `N` and 'choose >' would be shown.

(I confirmed it with/without choose-win.vim)

**By the way** 
https://github.com/Shougo/vimfiler.vim/issues/317
https://github.com/Shougo/vimfiler.vim/issues/321

彼らと同じように、個人的には昔の挙動のほうが好きです。
コードを見た感じ [この辺り](https://github.com/Shougo/unite.vim/commit/1bb46c56b4dc8a1f87a1014560c212fa6f272211#diff-3aaf85f50d5e77cb6d5c70cfd6dc9d78L320) のコードをオプションで選択できれば良さそうなのですが、オプション化していない理由などがあるのでしょうか？特に理由があるわけではないならば

1. `g:unite_source_vimfiler_new_file_behavior = '' or 'open' or ...` みたいな変数を用意
2. 上記にしたがって 過去のコードの呼び出しを決める

というように修正したいのですがどうでしょう？

**Comment by Shougo** [comment]
> `<Plug>(vimfiler_new_file)` show 'choose >' step but it won't open the created buffer thus the step is just annoying. And after creation, the focus is on the buffer I choose thus I have to re-focus vimfiler window and have toselect the newly created file while the cursor is not on the file created.

Oh, it is bug.  Fixed.

> 彼らと同じように、個人的には昔の挙動のほうが好きです。
コードを見た感じ この辺り のコードをオプションで選択できれば良さそうなのですが、オプション化していない理由などがあるのでしょうか？特に理由があるわけではないならば

そういう要望が一部あることも理解していますが、却下します。

理由1：オプション追加は好きではないので避けたい。とくに挙動をオンオフで制御するグローバル変数的なもの

理由2：vimfilerのオプションをunite側でいじるのは実装として気持ちが悪い

**Comment by lambdalisue** [comment]
なるほど、わかりました。どうしても必要な場合は独自実装で乗り切ります。ありがとうございました！
