### ISSUE TITLE
edit file in previous buffer that was active

### ISSUE THREAD

**Issue by Gufran** [Shougo/vimfiler.vim#334]
When using vimfiler as a sidebar explorer it is hard to edit files in previous buffer that was focused, vimfiler will always open the file in current buffer and if the buffer width is small it is completely worthless.

Here is my configuration

```
call vimfiler#custom#profile('default', 'context', {
            \ 'explorer' : 1,
            \ 'winwidth' : 30,
            \ 'winminwidth' : 30,
            \ 'toggle' : 1,
            \ 'columns' : 'type',
            \ 'explorer-columns' : 'type',
            \ 'status' : 1,
            \ 'safe' : 0,
            \ 'split' : 1,
            \ 'no-quit' : 1,
            \ 'force-hide' : 1,
            \ })
```

you can try this series of actions inside a directory (think - as horizontal split and | as vertical split)

In buffer 1
`:sp` -> 1 - 2, 
`:vsp` -> 1 - (2 | 3)
`:sp` -> 1 - (2 - 3 | 4)
`:VimFiler`, -> `o` or `e` -> will open a file in left split with width 30

Using `E` gets the work done but then I have an extra split that I don't want.
Is it possible to somehow configure vimfiler to open a file in last buffer that was focused before I switch to vimfile. So If I was in split 4 and I open vimfiler and choose a file it should open the file in split 4.

**Comment by Shougo** [comment]
Reproduced.  But your options are wrong.
Correct options:

```vim
call vimfiler#custom#profile('default', 'context', {
            \ 'explorer' : 1,
            \ 'winwidth' : 30,
            \ 'winminwidth' : 30,
            \ 'toggle' : 1,
            \ 'columns' : 'type',
            \ 'explorer_columns' : 'type',
            \ 'status' : 1,
            \ 'safe' : 0,
            \ 'split' : 1,
            \ 'no_quit' : 1,
            \ 'force_hide' : 1,
            \ })
```
