### ISSUE TITLE
GVim Crashes on VimResized callback

### ISSUE THREAD

**Issue by cemaleker** [Shougo/vimfiler.vim#335]
I just found out vimfiler causes a crash with SIGBUS on VimResized callback when vimfiler open during resize operation. I don't really know how to debug this. What kind of debug information can I provide to figure out the problem?

**Comment by Shougo** [comment]
I cannot reproduce the problem.
So, I cannot help you.
I recommend for you to update your Vim.

**Comment by cemaleker** [comment]
The vim I was using was latest gvim release from archlinux repositories. Upon further inspection realized the problem is experienced on gvim when a Unite window is fullscreen. Switched to standard terminal vim. Then problem is gone.  

But it's good to mention in documentations or somewhere with gvim resize actions might terminate the app with Unite.

**Comment by Shougo** [comment]
I don't think so.
I use GVim 7.4.922(latest version) in Manjaro Linux.
But I cannot reproduce it.

If you want to use full screen GVim, you should use `lambdalisue/vim-fullscreen` plugin.
