### ISSUE TITLE
Open file in last active window

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#336]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimfiler
filetype plugin indent on

call vimfiler#custom#profile('default', 'context', {
            \ 'direction' : 'topleft',
            \ 'split': 1,
            \ 'force_quit': 1,
            \ })
```

Now, as in the GIF, do the following:

i) Open Gvim and edit two files (for example `vimrc` and `vimrc_min`)
ii) Run `:vsplit` and once the split window opens, switch to that window and  do `:bn` to load the second file.
iii) From this split window run `:VimFiler -find`
iv) Once the vimfiler buffer opens select another file such as `syntax/matlab.vim` and open it pressing `<Enter>`

You will see that this third file opens in the window on the left side. However the `:VimFiler -find` command was called from the window on the right side (on the right split) so I expect the file to open in this split (and not in the left one as it currently does).

![blahhh](https://cloud.githubusercontent.com/assets/2583971/11025326/878c8c74-8678-11e5-913f-695bda6c6af3.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!
