### ISSUE TITLE
it would have been open in the split and open the file in vimfiler

### ISSUE THREAD

**Issue by wanshot** [Shougo/vimfiler.vim#339]
Hi, I'm use MacVim version7.4.922

after version d3ce50204d5255615f965f9ec804667f10c270a1,
 
Use the vimfiler close once you open the file

File would have been opened by then once again open the file split

![vimfiler_split](https://cloud.githubusercontent.com/assets/13720034/11318459/e2d80f64-9095-11e5-9871-84832fab525d.gif)

**Comment by Shougo** [comment]
Hm ....
I want to reproduce the problem.
Please create minimal .vimrc less than 50 lines and the reproduce ways from Vim starting.

And please explain the expected and current behaviour.

**Comment by wanshot** [comment]
I tried it in minimal .vimrc, use vimfiler and neobundle and unite

This is an gif of the vimfiler master revision.
![master](https://cloud.githubusercontent.com/assets/13720034/11324042/55bdfb2e-9168-11e5-989a-feda07b224e8.gif)

This is an gif of the vimfiler 755429b5ec6f0cf302d83a80ec8b8597456916e8 revison.
![before](https://cloud.githubusercontent.com/assets/13720034/11324044/7ad9ad5e-9168-11e5-9da0-5a0363972d23.gif)

When I close a file after having opened the file using a command and opened again, I hope you to make a window size when a file opened the same as the first when you open

**Comment by Shougo** [comment]
Fixed.

**Comment by wanshot** [comment]
Thank You :smile:
