### ISSUE TITLE
Unknown function error when starting Gvim

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#341]
With the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/OneDrive/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')


if has('vim_starting')
    execute 'set runtimepath+=' . expand('$DOTVIM/bundle/neobundle')
endif
call neobundle#begin(expand('$DOTVIM/bundle/'))
NeoBundle 'Shougo/vimfiler', {'explorer' : 1 }
call neobundle#end()

call vimfiler#custom#profile('default', 'context', {'direction' : 'topleft'})
call vimfiler#set_execute_file('pdf,PDF', 'SumatraPDF')

```

I get the following message when starting Gvim:

![screenshot-01-12-2015_12-39-27](https://cloud.githubusercontent.com/assets/2583971/11505322/9eebab40-9828-11e5-8432-0927cdb95747.png)

**Comment by wsdjeg** [comment]
same issue

**Comment by Shougo** [comment]
You must change the `NeoBundle` line like below.

```vim
NeoBundle 'Shougo/vimfiler', {'explorer' : 1, 'lazy' : 0 }
```

Or

```vim
NeoBundle 'Shougo/vimfiler', {'explorer' : 1 }

**Comment by petobens** [comment]
Thank you

**Comment by wsdjeg** [comment]
![2015-12-05 19-24-09](https://cloud.githubusercontent.com/assets/13142418/11607549/c96bb6b6-9b85-11e5-9db1-4fd35f2f2745.png)
here is my vimrc but still get the unknow func error

**Comment by wsdjeg** [comment]
fixed by put it behind neobundle#end()

**Comment by Shougo** [comment]
It is feature.
`rtp` is set after `neobundle#end()` to optimize.
If you want to set `rtp` directly, you should use `force` flag.

**Comment by wsdjeg** [comment]
thank you ,i think put rtp after neobundle#end() is safty
