### ISSUE TITLE
how to adjust the vimfiler buffer window position?

### ISSUE THREAD

**Issue by cposture** [Shougo/vimfiler.vim#342]
by default，vimfiler window always place in the left of window.But how to change the buffer to the right of window when input VimFiler or VimFilerExploerer?
I've add the follow to .vimrc, but no effect. thanks!
call vimfiler#custom#profile('default', 'context',{'direction' : 'topright'})

**Comment by Shougo** [comment]
```vim
call vimfiler#custom#profile('default', 'context',{'direction' : 'rightbelow'})
```

`:topright` is invalid command.

**Comment by cposture** [comment]
It works!
Thanks
