### ISSUE TITLE
Issues on_BufReadCmd and on_FileReadCmd

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/vimfiler.vim#343]
#### `read foo:bar` does not throw exception

By this commit
https://github.com/Shougo/vimfiler.vim/commit/86da09785b2768937df9a5894989bc677f4a590d

But it should raise exception. You may should check `autocmd FileReadCmd` I guess

#### `new foo:bar` or `read foo:bar` break a current unite instance

[s:on_BufReadCmd](https://github.com/lambdalisue/vimfiler.vim/blob/HEAD/autoload/vimfiler/handler.vim#L47) or  [s:on_FileReadCmd](https://github.com/Shougo/vimfiler.vim/blob/HEAD/autoload/vimfiler/handler.vim#L97) call [unite#start#vimfiler_check_filetype](https://github.com/lambdalisue/unite.vim/blob/HEAD/autoload/unite/start.vim#L214) and that call [unite#init#_current_unite](https://github.com/lambdalisue/unite.vim/blob/HEAD/autoload/unite/init.vim#L253) and a new unite instance is created based on `source_name`, `source_args`, and `context` but when `foo:bar` is specified, most of time there are no valid source thus the newly created unite have an empty `sources`

#### Question

1. Why do you need to call `on_BufReadCmd` or `on_FileReadCmd` for `new foo:bar` or `read foo:barP and re-configure the current unite interface?
2. It would be great if vimfiler use an independent unite of a selected line instead of the current unite I guess but why don't you do that (I'm sure there are some reason which I don't know)

In short. I'm sorry but I cannot fix this.... orz

**Comment by lambdalisue** [comment]
Shall I send a PR?

**Comment by Shougo** [comment]
OK.  Please send it.

**Comment by lambdalisue** [comment]
うーん・・・直そうと思ったのですが、ちょっと難しそうです。
1. `on_BufReadCmd` や `on_FileReadCmd` を呼ぶ必要性がコードからは理解できませんでした
2. 上記にて unite インスタンスを更新する必要性が理解できませんでした
3. VimFiler が独自に unite インスタンスを持ち、選択行に合わせて `source` などを設定する方が良さそうだと感じたのですが、まぁそれを行わない理由ありますよね・・・それがわからないので

などちょっとコードを読んだだけでは unite と vimfiler の連携が複雑で難しいです。申し訳ありませんがお時間あるときに良い修正をお願いいたします。

**Comment by lambdalisue** [comment]
ちなみに

1. `:VimFiler` を開く
2. `:new foo:bar` で `foo:bar` という名前のバッファを開く　or `:read foo:bar` で `foo:bar` を読み込む
3. `:VimFiler` に戻りファイルを開こうとする

で再現します。また、`foo:bar` が与えられた際のそれぞれの引数は

```vim
a:source_name = 'foo'
a:source_args = ['bar']
```

となります。

**Comment by Shougo** [comment]
> 1. on_BufReadCmd や on_FileReadCmd を呼ぶ必要性がコードからは理解できませんでした

metarw や netrw のように汎用的なファイルプラグインも意図していたのです。結果的に中途半端になってしまいましたが。

> 2. 上記にて unite インスタンスを更新する必要性が理解できませんでした

それは unite が副作用を持ってしまっているからです。正直設計ミス。

> 3. VimFiler が独自に unite インスタンスを持ち、選択行に合わせて source などを設定する方が良さそうだと感じたのですが、まぁそれを行わない理由ありますよね・・・それがわからない

独自の unite インスタンスは持っています。しかし、unite 側の状態の分離が中途半端なのです。
あまりにひどいので vimfiler の状態管理部分は最近直しましたが、unite 側には手を付けられていません。

**Comment by lambdalisue** [comment]
なるほど・・・さすがに手をつけられない部分でしたね。
ご修正ありがとうございます。確認してみます

**Comment by lambdalisue** [comment]
確認しました！ありがとうございました :+1:
