### ISSUE TITLE
Can't open VimFilerExplorer in no-split mode

### ISSUE THREAD

**Issue by yusiwen** [Shougo/vimfiler.vim#346]
Thanks for your great work. I'm new to vimfiler, this is my settings:

```
" vimfiler {{{
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_enable_clipboard = 0
  " [unite] is difined in 'unite.vim' setting above
  nnoremap <silent> [unite]q :<C-u>VimFiler -buffer-name=files -split -simple -winwidth=40 -toggle -no-quit<CR>
" }}}
```

When hitting `[unite]q`, VimFiler opens in left split window, it's alright. But when I input `:VimFilerExplorer`, it still opens in left split window and is not in explorer mode(still in simple mode). How should I open VimFilerExplorer in full window mode(no-split)? Thanks.

**Comment by Shougo** [comment]
Hm.... `:VimFilerExplorer` is simple and split like NERDTree.
I don't know why you want to use it in no-split mode.
But you can use it by below command(I don't know it is useful).

```vim
:VimFilerExplorer -no-split -explorer-columns=type:size:time
```

**Comment by yusiwen** [comment]
It's my misunderstanding. I thought `VimFilerExplorer` was a file explorer like Finder on mac with filename, size, date, etc informations, so there might be not enough space for it to open in split like NerdTree.

**Comment by Shougo** [comment]
Oh, OK.  If so, you can use `:VimFiler` command.
