### ISSUE TITLE
Can't run VimFiler with VimEnter

### ISSUE THREAD

**Issue by cdvv7788** [Shougo/vimfiler.vim#347]
Following the FAQ, i am trying to run VimFiler at start with:
```javascript
autocmd VimEnter * if !argc() | VimFiler | endif
```
But i get a blank page instead of the VimFiler (The title says VimFiler tho).

If i try to run VimFiler without the condition everything works as expected:
```javascript
autocmd VimEnter * VimFiler
```
I am new to vim/vimscript, so i am trying to figure out the issue.
For now i got it to work with:
```javascript
autocmd VimEnter * if !argc() | execute "VimFiler" | endif
```
What am i doing wrong or what do i need to do in order to make it work like in the FAQ?
I append my minimal .vimrc
```javascript
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
call vundle#end()
autocmd VimEnter * if !argc() | VimFiler | endif
```
Thanks!

**Comment by Shougo** [comment]
Fixed.
