### ISSUE TITLE
VimFilerExplorer doesn't open in current directory

### ISSUE THREAD

**Issue by fatih** [Shougo/vimfiler.vim#350]
The document for `:VimFilerExplorer` says it's equivalent to `VimFiler`:

```
:VimFilerExplorer [{options}...] [{path}]	*:VimFilerExplorer*
		Equivalent to |:VimFiler| except that it creates explorer
		vimfiler buffers.
```

The document for `:VimFiler` says that if **no** path is given it opens in current directory:

```
:VimFiler [{options}...] [[{source-name}:]{path}]
		Runs vimfiler. This command reuses a buffer if a vimfiler
		buffer already exists. >>>>   If you omit {path}, vimfiler opens
		current directory  <<<<  [[{source-name}:]{path}] arg is same as
		|:Unite|.  But you omit source name, "file" source will be
		used.  If {path} is directory, browse in {path} directory
		files.  If {path} is file, edit {path} file.
		{options} are options for a vimfiler buffer:
		|vimfiler-options|
```

But `:VimFilerExplorer` doesn't open a new directory if you open another buffer in another directory. `:VimFiler` works fine. Steps to reproduce:

* Open `~/text.go` 
* Call `:pwd` to see current directory
* Call `:VimFilerExplorer`, it works as expected
* Switch to another buffer in another directory, say `/tmp/hello.go`
* Call `:cd %:h` (to switch to the directory of `hello.go`, call `:pwd` to validate it (should say `/tmp`)
* Call `:VimFilerExplorer`, it **doesn't** work as expected. It shows still `~`, not `/tmp`

However the above steps works fine with `:VimFiler`.

**Comment by fatih** [comment]
For now I'm using this:

```
function! s:VimFilerExplorerFix()
  let dir = getcwd()
  exec 'VimFilerExplorer '. dir
endfunction

noremap <Leader>n :<C-u>call <SID>VimFilerExplorerFix()<cr>
```

Which fixes my problem.

**Comment by Shougo** [comment]
It is the feature.

` This command reuses a buffer if a vimfiler buffer already exists.`

You should use `:VimFilerBufferDir -explorer` instead of it.

**Comment by fatih** [comment]
Thanks it worked for me :+1:
