### ISSUE TITLE
what fonts do you use ,why my vimfiler 's icon looks diff

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/vimfiler.vim#352]
![2016-01-17 21-48-49](https://cloud.githubusercontent.com/assets/13142418/12377777/4197eeac-bd64-11e5-883c-2573f8bef6de.png)

**Comment by Shougo** [comment]
My fonts are:

```vim
  " For Linux.
  set guifontwide=VL\ Gothic\ 13
  set guifont=Courier\ 10\ Pitch\ 13.5
```

**Comment by wsdjeg** [comment]
Ok ,as I know your are not using win, so whty do not use vim in terminal ,now you are using gvim ?

**Comment by Shougo** [comment]
* GVim is faster

* Vim cannot use some keys(terminal limitation)

* Vim cannot use some features

**Comment by wsdjeg** [comment]
so, that is why you use givm+vimshell

**Comment by Shougo** [comment]
Yes
