### ISSUE TITLE
AirLine: conflict settings

### ISSUE THREAD

**Issue by konofeev** [Shougo/vimfiler.vim#356]
Set setting vim-airline (https://github.com/vim-airline/vim-airline)
`let g:airline_enable_bufferline = 1`
or
`let g:airline#extensions#tabline#enabled = 1`

When opening vimshell
![Image of vimshell](https://cloud.githubusercontent.com/assets/9324574/12914053/4e6ebaee-cf33-11e5-80a8-cfc21583879d.jpg)

I checked on an empty configuration
Thanks for the help

**Comment by Shougo** [comment]
This is *vimfiler* issue tracker.

And please create minimal .vimrc.

> I checked on an empty configuration

What your problem is?  It is not update the prompt?  I have not ESP skill.
