### ISSUE TITLE
"diff" function doesn't work in latest vimfiler version

### ISSUE THREAD

**Issue by jonesgy** [Shougo/vimfiler.vim#357]
Hi Shougo,

I encounter a vimfiler issue after git pull its latest version.

Reproduce steps:

1. Open vimfiler in Vim 7.4
2. Use "Tab" key to open other vimfiler window
3. Use "Space" key to select one file in vimfiler window 1 and vimfiler window 2
4. Use "A" key to open action items then select "diff" function
5. It shows bellowing errors
    [unite.vim] function unite#action#do..363..unite#action#do..371, line 18
    [unite.vim] Vim(let):E119: Not enough arguments for function: vimfiler#get_marked_files
    [unite.vim] Error occurred while executing "diff" action!

This function used to work in previous vimfiler version.

BTW, using "Space" key to select two folders in these two separate vimfiler windows then select "diffdir" function never works on my Vim.

**Comment by Shougo** [comment]
Fixed.  Please update unite.vim.

**Comment by jonesgy** [comment]
Hi Shougo,

I got bellowing error after update unite.vim

[unite.vim] function unite#action#do..363..unite#action#do..371, line 18
[unite.vim] Vim(let):E119: Not enough arguments for function: vimfiler#get_file
[unite.vim] Error occurred while executing "diff" action!

**Comment by Shougo** [comment]
Fixed.

**Comment by jonesgy** [comment]
Thanks!!

Issue resolved.
