### ISSUE TITLE
"dirdiff" function doesn't work

### ISSUE THREAD

**Issue by jonesgy** [Shougo/vimfiler.vim#358]
Hi Shougo,

Thanks for your help on #357 

I raise other issue related to "dirdiff" function which never works on my environment. Not sure it is a issue of DirDiff or not.

Reproduce steps:

1. Open vimfiler in Vim 7.4
2. Use "Tab" key to open other vimfiler window
3. Use "Space" key to select one folder in vimfiler window 1 and vimfiler window 2
4. Use "A" key to open action items then select "dirdiff" function
5. It shows bellowing errors

    "Candidates must be 2."

**Comment by Shougo** [comment]
It is feature.
You must select two candidates in one vimfiler.
Double filers are not supported.

**Comment by jonesgy** [comment]
Thanks for your answer.
