### ISSUE TITLE
I don't want all of the default key mappings

### ISSUE THREAD

**Issue by ranranking** [Shougo/vimfiler.vim#359]
I just want to disable some of the default key mappings. The default key mappings have some conflicts with my own mappings. If I set vimfiler_no_default_key_mapings to 1, all the default key mappings just won't work, I have to map them one by one? Basically, I just want the K work as my own mappings.

**Comment by Shougo** [comment]
>  I have to map them one by one? 

@ranranking Yes.  Please do it.
