### ISSUE TITLE
Lags with a large tree

### ISSUE THREAD

**Issue by WscriChy** [Shougo/vimfiler.vim#360]
The plugin gives really noticeable lags when the tree gets bigger. Do you use any caching? Do you plan too? That could be nice.

**Comment by WscriChy** [comment]
Oh my mistake I see you do use it. But any idea how to improve on the usage of the plugin with large trees.

**Comment by Shougo** [comment]
PR is wellcome.
I think to fix it is very very hard.
You can see it in the other filers.

**Comment by Shougo** [comment]
> The plugin gives really noticeable lags when the tree gets bigger. Do you use any caching? Do you plan too? That could be nice.

The cache is already implemented.
