### ISSUE TITLE
Opening a .pdf file

### ISSUE THREAD

**Issue by Bearsden** [Shougo/vimfiler.vim#361]
I've recently started using your vimfiler, which I found extremely useful. I am greatly thankful for it. But I have a little problem on which I wish to seek your advice.
 
I wish to open a .pdf file by selecting Preview or Skim on OS X El Capitan. An example of my .vimrc is

```
" VimFiler
let g:vimfiler_as_default_explorer = 1
let g:vimfiler_execute_file_list = {
	\   'pdf' : ['preview', 'skim']
	\ }
autocmd FileType vimfiler nmap <buffer> X <Plug>(vimfiler_execute_vimfiler_associated)
" NeoBundle
set nocompatible
filetype off
if has('vim_starting')
        set rtp+=$HOME/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'
call neobundle#end()
NeoBundle 'Shougo/unite.vim.git'
NeoBundle 'Shougo/vimfiler.vim'
filetype plugin indent on
```

However, pressing ``X`` gives the following error message:
>[unite.vim] [vimfiler/execute] Command "preview" is not executable file. [unite.vim] unite buffer "vimfiler/execute" candidates are empty

I wonder if you can tell me what is wrong with the above .vimrc?

Your advice would be greatly appreciated.

**Comment by Shougo** [comment]
`preview` command must be executable from Vim.
Please check it.

**Comment by Bearsden** [comment]
Thanks for your reply.
The following commands from Vim work fine:

``:!open -a preview file.pdf``
``:!open -a skim file.pdf``

**Comment by Shougo** [comment]
`preview` must be command name.
`open -a skim` is not supported.
