### ISSUE TITLE
Narrow windows when using bookmarks

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#362]
Consider the following minimal vimrc:

```vim
set nocompatible

let $DOTVIM = expand('~/.vim')

set runtimepath+=$DOTVIM/bundle/vimfiler/
set runtimepath+=$DOTVIM/bundle/unite
filetype plugin indent on

call vimfiler#custom#profile('default', 'context', {
        \ 'direction' : 'topleft',
        \ 'split': 1,
        \ 'winwidth' : 40,
        \ 'force_quit': 1,
        \ 'safe': 0
        \ })

augroup ps_vimfiler
    au!
    au FileType vimfiler nnoremap <silent><buffer>b <C-u>:VimFiler bookmark:<CR>
augroup END
```

Now open MacVim and do the following (as in the GIF):
1. Add some bookmark: `:UniteBookmarkAdd /Users/Pedro`
2. open Vimfiler: `VimFiler` and press `b` to open the bookmarks 
Here you will see that the bookmarks open in a new window when I expect it to open in the same Vimfiler window
3. Navigate to some file, for instance your `bash_profile` and open it with  `<ENTER>`
You will see that the file opens in the same narrow window as the vimfiler buffer. I expect the vimfiler buffer to close and the file to open in a new full window.

![vimfiler](https://cloud.githubusercontent.com/assets/2583971/13550169/32ea14e0-e2f6-11e5-9123-8b66ab136a7c.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!
