### ISSUE TITLE
Unknown function: vimfiler#custom#profile

### ISSUE THREAD

**Issue by alexbooker** [Shougo/vimfiler.vim#364]
Here's my minimal _init.vim_:

```vim
if has('vim_starting')
	set runtimepath+=/home/booker/.config/nvim/bundle/neobundle.vim/
endif

call neobundle#begin()
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim', {'build' : 'make'}
NeoBundleLazy 'Shougo/unite.vim', {
			\ 'on_cmd': 'Unite'
			\ }
NeoBundleLazy 'Shougo/vimfiler.vim', {
			\ 'depends': 'Shougo/unite.vim',
			\ 'on_map': '<Plug>',
			\ 'on_path': '.*',
			\ 'on_cmd': 'VimFiler'
			\ }
call neobundle#end()
filetype plugin indent on
NeoBundleCheck

call vimfiler#custom#profile('default', 'context', {
			\  'safe': 0,
			\  'explorer': 1,
			\  'winwidth': 25,
			\  'split': 1,
			\  'direction': 'topleft',
			\  'auto_expand': 1,
			\  'no_quit': 1,
			\  'force_hide': 1,
			\  'parent': 0,
			\  'toggle': 1,
			\ })
```

When I open Neovim I get an error:

```
booker [~/.config/nvim] → nvim init.vim

Error detected while processing /home/booker/.config/nvim/init.vim:
line   34:
E117: Unknown function: vimfiler#custom#profile
Press ENTER or type command to continue

```

Any help would be very much appreciated. Thanks.

**Comment by alexbooker** [comment]
I think I know what's wrong...

**Problem**

```
NeoBundleLazy 'Shougo/vimfiler.vim', {
            \ 'depends': 'Shougo/unite.vim',
            \ 'on_map': '<Plug>',
            \ 'on_path': '.*',
            \ 'on_cmd': 'VimFiler'
            \ }
```

This command tells NeoBundle to **only** load VimFiler when the `:VimFiler` command is run.

In my _init.vim_ I write `vimfiler#custom#profile`. This line is called **immediately**. At the time this line is called, VimFiler isn't in the runtime path because I haven't run `:VimFiler` yet.

**Solution 1**
Solution 1 is just to load VimFiler eagerly:

```
NeoBundle 'Shougo/vimfiler.vim', {
            \ 'depends': 'Shougo/unite.vim',
            \ }
```

**Solution 2**

Solution 2 is to call `vimfiler#custom#profile` when VimFiler is sourced. 

In _init.vim_ write:

```
if neobundle#tap('vimfiler.vim')
	let neobundle#hooks.on_source = 'vimfiler.vim'
endif
```

In a separate file called _vimfiler.vim_, write:
```
let g:vimfiler_as_default_explorer = 1
call vimfiler#custom#profile('default', 'context', {
      \  'safe': 0,
      \  'explorer': 1,
      \  'winwidth': 25,
      \  'split': 1,
      \  'direction': 'topleft',
      \  'auto_expand': 1,
      \  'no_quit': 1,
      \  'force_hide': 1,
      \  'parent': 0,
      \  'toggle': 1,
      \ })
call neobundle#untap()
```

**Comment by Shougo** [comment]
Yes.  It is the feature.

**Comment by kutsan** [comment]
I'm using vim-plug, how can I deal with this problem? Looks like vim-plug has no such feature?

**Comment by Shougo** [comment]
@kutsan I don't know vim-plug problem.
Please upload the example.

**Comment by Shougo** [comment]
@kutsan If you set vimfiler as lazy loaded plugin, you cannot call vimfiler functions.
It is feature.  You should not vimfiler as lazy loaded plugin.
vim-plug's lazy loading feature is very limited. Not easy to configure.
dein.vim or neobundle.vim can do it though.

**Comment by kutsan** [comment]
https://github.com/kutsan/dotfiles/blob/15505d9b26cc56c303e81d7692598a1ca3c74500/.vim/vimrc#L269-L319

Here is my `vimrc`.

https://github.com/kutsan/dotfiles/blob/15505d9b26cc56c303e81d7692598a1ca3c74500/.vim/vimrc#L277-L287

Uncommenting these lines do not affect anything. Even moving those lines after `call plug#end()` line does not affect either. Is there anything I can do? Using deprecated variables will do the work, can I use them? Will you remove them in future?

And yeah, it's pretty hard to dealing with that limited features.

**Comment by Shougo** [comment]
OK.  It is not related to the problem.
It is another problem.

Please create the new issue and the reproduce ways from Vim starting.
I will test it.

Note:  Please read the other issues.  It must be testable for me.

**Comment by kutsan** [comment]
Okay thanks for spending your time! I'll create as soon as possible.

**Comment by kutsan** [comment]
For the sake of searchability, new issue located at #405.

**Comment by kutsan** [comment]
Also, for others, my original problem was I wanted to include `vimfiler#custom#profile()` function before `plug#end()`. (Because of my `vimrc`s code organization) I achieved that with writing Plug definition like this.

```vim
Plug 'Shougo/vimfiler.vim', { 'on': [] } | call plug#load('vimfiler.vim')
```

That way, vimfiler will load immediately by default without lazy loading.

**Comment by Shougo** [comment]
@kutsan Yes, it is vim-plug feature.
