### ISSUE TITLE
Change vimfiler colors

### ISSUE THREAD

**Issue by minhdanh** [Shougo/vimfiler.vim#366]
Is there a way to customize the colors (directory, text...) in vimfiler? The document says it has a variable `g:vimfiler_extensions` to control vimfiler color syntax but I'm not sure if this is the way and how to do it.

**Comment by Shougo** [comment]
Change the highlights defined in https://github.com/Shougo/vimfiler.vim/blob/master/syntax/vimfiler.vim.
