### ISSUE TITLE
Open bookmarks in the same window

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#369]
Consider the following minimal vimrc:

```vim
set nocompatible

let $CLOUD_DIR = expand('$HOME/OneDrive/')
let $DOTVIM = expand('$CLOUD_DIR/vimfiles')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/unite.vim/
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/vimfiler/
filetype plugin indent on

call vimfiler#custom#profile('default', 'context', {
        \ 'direction' : 'topleft',
        \ 'split': 1,
        \ 'winwidth' : 40,
        \ 'force_quit': 1,
        \ 'status' : 1,
        \ 'columns' : '',
        \ 'safe': 0
        \ })

augroup ps_vimfiler
    au!
    au FileType vimfiler call s:vimfiler_settings()
augroup END

function! s:vimfiler_settings()
    nnoremap <silent><buffer>b <C-u>:VimFiler bookmark:<CR>
endfunction
```
Now open vim and run:
i) `:VimFiler`
ii) Inside the Vimfiler buffer press `b` to open the bookmarks
You will see (as in the GIF) that a new vimfiler window opens. I expect the bookmarks to open in the current vimfiler window.
![jul-26-2016 16-04-05](https://cloud.githubusercontent.com/assets/2583971/17151620/a8e66cc4-534a-11e6-97df-4107cca4cdbd.gif)

**Comment by Shougo** [comment]
Please use below mapping and update unite.vim.

```vim
nnoremap <silent><buffer>b <C-u>:VimFiler bookmark:/<CR>
```

**Comment by petobens** [comment]
When I use the above mapping and press enter to get into a bookmark that bookmark is empty (i.e no files are shown):

![jul-27-2016 09-40-28](https://cloud.githubusercontent.com/assets/2583971/17175487/3637f5aa-53de-11e6-844a-b6bfb84770ae.gif)

**Comment by Shougo** [comment]
Fixed

**Comment by petobens** [comment]
Now I see files but I have again the problem of original post: the bookmarks open in a new window instead of the current one.

**Comment by Shougo** [comment]
@petobens It is feature.
vimfiler opens new vimfiler window.

**Comment by Shougo** [comment]
Please change the path by `<Plug>(vimfiler_cd_input_directory)` instead `:VimFiler`.

**Comment by petobens** [comment]
Mmm I understand it might be a feature but onsider the following GIF:
![aug-09-2016 23-38-09](https://cloud.githubusercontent.com/assets/2583971/17540155/700666ac-5e8a-11e6-94ef-77775f1137ee.gif)

When I open the file from the bookmark it opens in the same window as the newly created bookmarked window and therefore my whole original window layout gets messed up.

> Please change the path by <Plug>(vimfiler_cd_input_directory) instead :VimFiler.
I'm sorry but I don't quit understand what you mean. Can you explain it please? Thanks!

**Comment by Shougo** [comment]
`<Plug>(vimfiler_cd_input_directory)` is mapped to `I` key.
You can change the current directory to `bookmark:` using it.

**Comment by petobens** [comment]
Ok, finally understood what you meant. The problem with the `<Plug>(vimfiler_cd_input_directory)` is that it autocompletes to the current working directory so when I use `nmap <buffer>b <Plug>(vimfiler_cd_input_directory) bookmark:/<CR>` and I'm in the `/Users/Pedro/OneDrive/vimfiles/` directory then the mapping attempts to take me to `/Users/Pedro/OneDrive/vimfiles/bookmark:/` which obviously doesn't exit. Can I avoid autocompletion of the current directory? i.e if I open vimfiler and press `I` and erase everything in command line and just write `:bookmark/` it indeed opens the  bookmark directory.
![aug-12-2016 12-49-06](https://cloud.githubusercontent.com/assets/2583971/17628444/baedbe56-608b-11e6-991a-c329aaa0b0da.gif)

**Comment by Shougo** [comment]
`nmap <buffer> B  <Plug>(vimfiler_cd_input_directory)<C-u>bookmark:`

**Comment by petobens** [comment]
Thank you!!
