### ISSUE TITLE
Multiple vimfiler buffers being opened in the same window

### ISSUE THREAD

**Issue by dylanscott** [Shougo/vimfiler.vim#371]
I'm encountering an issue where multiple invocations of `:VimFilerExplorer -find` in the same window result in a new vimfiler buffer being created each time.

Steps:
1. Open vim and navigate to a file.
2. Run `:VimFilerExplorer -find`
3. Switch from the vimfiler buffer back to the previous buffer and re-run `:VimFilerExplorer -find`

It appears this was introduced with 58e9a6780e7437cec3c2c6ab4e29aecd518c18f7. Checking out the previous commit fixes it for me.

**Comment by Shougo** [comment]
Fixed.
