### ISSUE TITLE
what's the relationship between vimfiler and unite?

### ISSUE THREAD

**Issue by hatelove85911** [Shougo/vimfiler.vim#373]
- I've roughly gone through the vimfiler documentation several times. But I still can't figure out what's the relationship between vimfiler and unite. Could you explain roughly?

- and in the documentation, the interface command of vimfiler is `:VimFiler [options] [sourcename:] [path]`, what are the valid source for vimfiler?? can I use the sources of unite.vim, like: yankhistory, file_rec/async or mru???

- what's the difference between all those different mode of vimfiler buffer: simple, double, explorer??

**Comment by Shougo** [comment]
> I've roughly gone through the vimfiler documentation several times. But I still can't figure out what's the relationship between vimfiler and unite. Could you explain roughly?

unite.vim is used to get files and do file operations.

> and in the documentation, the interface command of vimfiler is :VimFiler [options] [sourcename:] [path], what are the valid source for vimfiler?? can I use the sources of unite.vim, like: yankhistory, file_rec/async or mru???

It is unite.vim source name.  But some sources only supports the feature.
For example, bookmark source.

> what's the difference between all those different mode of vimfiler buffer: simple, double, explorer??

You should try it...
`:VimFiler -simple`
`:VimFiler -double`
`:VimFiler -explorer`

simple is to open simplified buffer.
double is to open double buffer.  You can do file operations to another vimfiler buffer directory.
explorer is tree mode.  You can use vimfiler as NERDTree like.
