### ISSUE TITLE
new feature requested: enter insert mode to fuzzy filter files or directories

### ISSUE THREAD

**Issue by hatelove85911** [Shougo/vimfiler.vim#375]
thanks for the great plugin.

I want to propose a new feature just as in unite's source file_rec/async, in those sources , you can type I to enter insert mode, and keep typing to fuzzy match results.

It would be great  if this kind of feature can be supported in vimfiler.  So user can choose to find a file by expanding the tree structure manually or he can choose to type key words of the file he wants to find and vimfiler will do fuzzy match to narrow down the results. The fuzzy match should be done for nodes which are not expanded yet as well. If some unexpanded nodes matches what user typed. then those nodes will be expanded to show the matching entry. Other nodes(files) doesn't match are hidden.

**Comment by Shougo** [comment]
It is complex feature.
I don't want to add the complexity.
My main work is to develop denite.nvim.
