### ISSUE TITLE
Hide current and parent directory lines in expanded tree 

### ISSUE THREAD

**Issue by lucerion** [Shougo/vimfiler.vim#376]
Is it possible to hide current (.) and parent (..) lines in expanded tree? (or just current line)

Now:
```
.
..
dir-1
dir-2
  .
  ..
  sub-dir-1
  sub-dir-2
dir-3
```

After:
```
..
dir-1
dir-2
  sub-dir-1
  sub-dir-2
dir-3
```
or
```
..
dir-1
dir-2
  ..
  sub-dir-1
  sub-dir-2
dir-3
```

**Comment by Shougo** [comment]
> Is it possible to hide current (.) and parent (..) lines in expanded tree? (or just current line)

Please upload minimal vimrc less than 50 lines.
I will check it.

**Comment by lucerion** [comment]
It reproduces without any vim settings, but with this vimfiler options (unite.vim and vimproc.vim installed):

```viml
let g:vimfiler_as_default_explorer = 1
let g:vimfiler_expand_jump_to_first_child = 0
let g:vimfiler_ignore_pattern = ' '
let g:vimfiler_time_format = '%Y-%m-%d %H:%M'
let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_readonly_file_icon = '×'
if isdirectory(expand('~/.vim/bundle/vimfiler.vim'))
  call vimfiler#custom#profile('default', 'context', { 'columns': 'size' })
endif
```

Looks like issue in the ignore pattern option - without it everything is ok:
```
let g:vimfiler_ignore_pattern = ' '
```

**Comment by Shougo** [comment]
It is unite.vim problem.
Please update unite.vim.

**Comment by lucerion** [comment]
Now it works as expected. Thank you, @Shougo!
