### ISSUE TITLE
-force-quit and -edit-action=choose doesn't update statusline for current window

### ISSUE THREAD

**Issue by tweekmonster** [Shougo/vimfiler.vim#377]
This issue is very old, but I couldn't figure out if the problem was in vimfiler, unite, airline, or my own scripts.  I just found that the cause is in unite.vim, but I think it's a defect in vimfiler.  This is how I'm using the `:VimFiler` command:

```
:VimFiler -find -project -split -simple -winwidth=35 -toggle -force-quit -edit-action=choose
```

When a file is chosen, the vimfiler window is closed, then `unite#helper#choose_window()` is called.  It then calls `unite#helper#choose_window()` to get the windows that should have the statusline updated:

```vim
function! unite#helper#get_choose_windows() abort "{{{
  return filter(range(1, winnr('$')), "v:val != winnr()
        \ && !getwinvar(v:val, '&previewwindow')
        \ && (getwinvar(v:val, '&buftype') !~# 'nofile'
        \   || getwinvar(v:val, '&buftype') =~# 'acwrite')
        \ && !getwinvar(v:val, '&filetype') !=# 'qf'")
endfunction"}}}
```

Since the vimfiler window is closed at this point, `v:val != winnr()` no longer refers to the vimfiler window.  As a result, it excludes the wrong window from the statusline updates.

Commenting this [mappings.vim#L628-L630](https://github.com/Shougo/vimfiler.vim/blob/f2a2db7437bb1163e8e6b2d002dc063d1e0303ea/autoload/vimfiler/mappings.vim#L628-L630) fixes the issue, but causes the choice prompt to happen twice.

**Comment by Shougo** [comment]
Please create minimal vimrc and reproduce ways from Vim starting.
I cannot reproduce the problem.

**Comment by tweekmonster** [comment]
Minimal vimrc:

```vim
set runtimepath+=~/.config/nvim/plugins/unite.vim/
set runtimepath+=~/.config/nvim/plugins/vimfiler.vim/

nnoremap <localleader>v :VimFiler -find -project -split -simple -winwidth=35 -toggle -force-quit -edit-action=choose<cr>
```

[Video of the issue](https://share.esdf.io/3LaU4KniSd/Screen-Recording-2016-09-29-12-11-07.mp4).  Notice that whatever the current window is after vimfiler closes, the status doesn't change to show the choice key.

**Comment by Shougo** [comment]
Fixed.

**Comment by tweekmonster** [comment]
Thank you! 🎉
