### ISSUE TITLE
Denite Compatibility

### ISSUE THREAD

**Issue by JarrodCTaylor** [Shougo/vimfiler.vim#380]
Is vimfiler compatible with denite, or is there still a unite dependency?

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/379

**Comment by JarrodCTaylor** [comment]
So the answer is no, and currently the de-*** plugin that will replace it still needs to be written?

**Comment by Shougo** [comment]
Yes

**Comment by bookercodes** [comment]
Cannot wait until de-*** so I can make the switch to Denite !

**Comment by andreiglingeanu** [comment]
Yeah, same here!

**Comment by ljohnston** [comment]
Yes, same here! Would love to switch to Denite, but can't live without vimfiler!

**Comment by ljohnston** [comment]
So I just noticed... all of the issues related to vimfiler and the denite dependency are closed. Does that mean that there is not going be an update to work with Denite? Vimfiler will only ever work with Unite?

**Comment by Shougo** [comment]
> Vimfiler will only ever work with Unite?

Yes.
The next file explorer plugin is https://github.com/Shougo/defx.nvim (vaporware)

**Comment by Shougo** [comment]
Because, vimfiler implementation is very bad.  It is hard to extend.
It should be re-written.

**Comment by kutsan** [comment]
@Shougo Will you rewrite anytime soon? We are looking forward to. I think it's the best file manager even with Denite.

**Comment by Shougo** [comment]
> Will you rewrite anytime soon? We are looking forward to. I think it's the best file manager even with Denite.

I have started the design.

**Comment by oblitum** [comment]
The serious drawback with defx.nvim is that it's not Vim friendly despite denite working on Vim without needing yarp. I use both Vim and NeoVim, but really don't like the solution of embedding neovim for Vim for some plugins to work.

**Comment by Shougo** [comment]
> The serious drawback with defx.nvim is that it's not Vim friendly despite denite working on Vim without needing yarp, defx.nvim does require it.

Because, denite.nvim blocks Vim but defx does not.
Denite.nvim use different compatibility solution.
I think using nvim-yarp is better.

So I don't change defx's dependency.
