### ISSUE TITLE
Question regarding custom unite source

### ISSUE THREAD

**Issue by mhartington** [Shougo/vimfiler.vim#382]
Hey Shougo! So I recently moved over from nerdtree to vimfiler and had a question regarding custom unite sources. Now nerdtree has a really nice file-system related menu
![nerdtree-menu](https://cloud.githubusercontent.com/assets/2835826/21544683/39c52554-cd9f-11e6-895b-38afb6c578ca.gif)

And while vimfiler has similar functionality, I was planning on trying to recreate something similar in a unite source. There is also `<Plug>(vimfiler_choose_action)`, which has similar actions, but contains many things that I do not need. 

So my overall question is about direction. Are there any examples of how to grab a hold of the file/directory when calling the unite source?

**Comment by Shougo** [comment]
> So my overall question is about direction. Are there any examples of how to grab a hold of the file/directory when calling the unite source?

Nothing.
Because, the all actions are `file/directory` related.
