### ISSUE TITLE
VimFiler doesn't seem to be working correct with Symbolic Links

### ISSUE THREAD

**Issue by varmanishant** [Shougo/vimfiler.vim#383]
Create a folder called "folder" and then 'cd' into it and touch a file called "file".
`cd ~; mkdir "folder"; cd "folder"; touch "file";`
Create a symbolic link to "folder" called "Folder".
`cd ~; ln -s "folder" "Folder";`

Now open "folder" in VimFiler

Output: You see duplicate list of "file"

Expected: Symbolic links should be understood correctly.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please upload the minimal init.vim less than 20 lines.

**Comment by varmanishant** [comment]
I am sorry that I assumed this would be a problem in all systems. I figured that this setting caused the problem: `set wildignorecase`

However is that an expected behaviour? I removed this from my .vimrc

**Comment by Shougo** [comment]
Hm.  It seems Vim's feature.
I cannot fix it.

You should install vimproc.
If you install vimproc, vimfiler uses vimproc function instead of `glob()`.
