### ISSUE TITLE
Vimfiler with latest neovim results in segmentation fault

### ISSUE THREAD

**Issue by petobens** [Shougo/vimfiler.vim#385]
Hi @Shougo, not really sure how to reproduce this one but I recently updated neovim from 0.17 to HEAD and every time I use vimfiler I get the following error (and neovim segfaults):
```
Error detected while processing function vimfiler#mappings#smart_cursor_map[1]..vimfiler#get_filename:
line    2:
E716: Key not present in Dictionary: action__path
Press ENTER or type command to continueSegmentation fault: 11
```
Any ideas? Sorry for not providing a minimal vimrc.

**Comment by Shougo** [comment]
This is not vimfiler issue.
Unfortunately, neovim HEAD is broken.
some problems are fixed though.
Please update neovim as possible.

**Comment by petobens** [comment]
Ohhhh. Okay thanks and sorry for the noise.

**Comment by petobens** [comment]
Just for reference, my issue is the same as the one reported [here](https://github.com/neovim/neovim/issues/5883).
