### ISSUE TITLE
Show full file name

### ISSUE THREAD

**Issue by Gufran** [Shougo/vimfiler.vim#386]
VimFiler collapses any filename longer than the width of split (see screenshot), is there any way to disable this behaviour and show complete filename no matter how long?  
So for example `long-file-name.ext` should be printed as it is and not `long...ame.txt`.

If it cannot be configured then can you please point me to the code which does this conversion? I'll make necessary change in my files.

<img width="487" alt="screen shot 2017-01-18 at 3 25 22 pm" src="https://cloud.githubusercontent.com/assets/2152267/22059567/6e55f97a-dd93-11e6-8be2-fa2ea9c6d2fa.png">

**Comment by lambdalisue** [comment]
It is a bit different from your request but is hitting `<C-g>` on the candidate enough?

**Comment by Gufran** [comment]
I know about <c-g> but it gets really cumbersome even for a couple files in a row

**Comment by lambdalisue** [comment]
I see. By the way, I personally use the following to temporary maximize vimfiler to see.

```vim
" Zoom widnow temporary with <C-w>o {{{
function! s:toggle_window_zoom() abort
    if exists('t:zoom_winrestcmd')
        execute t:zoom_winrestcmd
        unlet t:zoom_winrestcmd
    else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
    endif
endfunction
nnoremap <silent> <Plug>(my-zoom-window)
      \ :<C-u>call <SID>toggle_window_zoom()<CR>
nmap <C-w>o <Plug>(my-zoom-window)
nmap <C-w><C-o> <Plug>(my-zoom-window)
"}}}
" Zoom widnow temporary with <C-w>o {{{
function! s:toggle_window_zoom() abort
    if exists('t:zoom_winrestcmd')
        execute t:zoom_winrestcmd
        unlet t:zoom_winrestcmd
    else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
    endif
endfunction
nnoremap <silent> <Plug>(my-zoom-window)
      \ :<C-u>call <SID>toggle_window_zoom()<CR>
nmap <C-w>o <Plug>(my-zoom-window)
nmap <C-w><C-o> <Plug>(my-zoom-window)
"}}}
```

In case if you are interested in.

**Comment by Shougo** [comment]
This is the feature.

**Comment by Gufran** [comment]
@Shougo I understand, and I appreciate that some time and efforts were put into making it the way it is, but I believe this should be configurable. It gets hard to navigate many files with a similar looking name.

Could you please at least point me to the code which transforms the name? I will make the change myself in my installation.

**Comment by Shougo** [comment]
Hint: `vimfiler#view#_get_print_lines()`
