### ISSUE TITLE
Execute custom function on directory

### ISSUE THREAD

**Issue by marcwimmer** [Shougo/vimfiler.vim#388]
hi,

thanks for the great plugin!

i would like to execute a custom function on a directory e.g. 

when user presses mm (make module) a function ProjectInitModule() shall be called.
i couldn't figure out how to do it. 
thanks for your help.

marc

**Comment by Shougo** [comment]
You should check the mappings implementation.

https://github.com/Shougo/vimfiler.vim/blob/master/autoload/vimfiler/mappings.vim
