### ISSUE TITLE
VimFiler crashes Vim

### ISSUE THREAD

**Issue by j-degreef** [Shougo/vimfiler.vim#390]
Hi,

I've installed VimFiler and Unite from github in Vim 7.4 (Linux Mint 18.1 64b) and as soon as I type :VimFiler the window appears but crashes Vim quite immediately. Same if I put :let g:vimfiler_as_default_explorer = 1 in my .vimrc
I've tested it with a minimal .vimrc (only vim-addon-manager loaded).
I attach the result of a debug with Verbose=15.
Please let me know what additional info I can give you or what I could test to try to solve this issue.

Best regards,
Jérôme
[VimFiler-debug.tar.gz](https://github.com/Shougo/vimfiler.vim/files/788625/VimFiler-debug.tar.gz)

**Comment by Shougo** [comment]
Vim 7.4 is very old version.
You should test it in Vim 8.0 latest version.

**Comment by j-degreef** [comment]
Wow, for a quick reply that's a quick reply ;)
I'll install Vim 8.0 and let you know if it is solved.

**Comment by j-degreef** [comment]
Ok, I've installed Vim 8.0 and the result was the same.
I then discovered that I had an old spell.vim in my plugin directory. Removing it solved the problem :)
Thanks for helping me.

**Comment by Shougo** [comment]
OK
