### ISSUE TITLE
VimFilerExplorer leave cursor

### ISSUE THREAD

**Issue by viniciusarcanjo** [Shougo/vimfiler.vim#392]
Hi @Shougo,

I am wondering if there is a way to make VimFilerExplorer behaves similar to Nerdtree's `go` shortcut. Basically, with Nerdtree (explorer), if you hit `go` the cursor still leaves in the Nerdree, so the focus doesn't change when you open a new file. It's useful for quickly glancing files, because the cursor stays in the tree and you can keep opening more files. 

I looked it up on the docs, but didn't find an appropriate way to do it. 

Thanks for your work! Much appreciated.

**Comment by Shougo** [comment]
Sorry, the feature is not implemented.
And I don't want to add more features in vimfiler.

**Comment by viniciusarcanjo** [comment]
OK. Thank you @Shougo.
