### ISSUE TITLE
How to auto open vimfiler window when gvim start ?

### ISSUE THREAD

**Issue by zhaochenyou** [Shougo/vimfiler.vim#393]
I'm new to vimfiler.vim, and I want to make vimfiler auto open when I start gvim, I didn't find any document about the configuration. Do I miss anything ?

**Comment by Shougo** [comment]
Please read FAQ section.

```
Q: To open a vimfiler buffer automatically when Vim starts up if no
files(arguments) were specified
>
	autocmd VimEnter * if !argc() | VimFiler | endif
<
```

**Comment by zhaochenyou** [comment]
thanks, I should read it more carefully, my bad.

**Comment by Shougo** [comment]
FAQ is the best section before asking.
