### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by camsn0w** [Shougo/vimfiler.vim#394]
Is there a keybind or command other than "Close" to close vimfilier?
Or is there a way I can have it auto close once I have opened a file?

**Comment by Shougo** [comment]
I cannot understand your issue.

Please describe it more clearly.

**Comment by camsn0w** [comment]
If I am using vimfilier, is there an easy way to close it

**Comment by Shougo** [comment]
OK.  You can use `<Plug>(vimfiler_close)`.
It is mapped to `_`.

Similar mappings:  `<Plug>(vimfiler_hide)` and `<Plug>(vimfiler_exit)`
