### ISSUE TITLE
Alternate buffer not restored on <Plug>(vimfiler_exit)

### ISSUE THREAD

**Issue by wilywampa** [Shougo/vimfiler.vim#395]
## Summary
Since https://github.com/Shougo/vimfiler.vim/commit/c88a634b9575c5e162e79da154beb628374e4542, Instead of returning to the previous buffer on `<Plug>(vimfiler_exit)`, a new buffer is created using `:enew`.

## Expected
vimfiler exits and returns to previous buffer

## Actual
vimfiler exits and creates a new empty buffer

## Steps to reproduce
1. Open a file in vim
2. Press `-` to run `:VimFilerBufferDir -find`
3. Press `Q` to exit vimfiler
4. Current buffer is now a new empty buffer instead of the buffer opened in step 1

## Minimal vimrc:

```vim
scriptencoding utf8
set runtimepath+=/Users/jniehus/Downloads/dev/vimfiler.vim
set runtimepath+=/Users/jniehus/Downloads/dev/unite.vim
nnoremap - :<C-u>VimFilerBufferDir -find<CR>
```

**Comment by Shougo** [comment]
Reproduced.
