### ISSUE TITLE
Allow overwriting / not setting some mappings

### ISSUE THREAD

**Issue by SidOfc** [Shougo/vimfiler.vim#396]
Hi Shougo!

My `<Leader>` key is set to `<Space>`. VimFiler uses `<Space>` and `<S-Space>` as mappings to mark files and it maps these always, I would like to see an option to disable or remap this (and even better, other keybinds) at will to ensure that I can use the following mappings defined in my .vimrc:

```
nmap     <Leader>1 <Plug>lightline#bufferline#go(1)
nmap     <Leader>2 <Plug>lightline#bufferline#go(2)
... snipped ...
nmap     <Leader>9 <Plug>lightline#bufferline#go(9)
```

I've checked the source of the plugin for any undocumented variables that I might be able to set but I'm probably too novice at vimscript to find them. Also, other workarounds suggest adding a `autocmd VimEnter` that will reoverwrite the keybindings but I have not managed to successfully do so.

Any help, aside from the plugin you've already provided is welcome, If I can help - I'll try too. Maybe I can figure it out and send a PR if you're busy but I'd rather have someone experienced take a look if possible.

Cheers!
SidOfc

**Comment by Shougo** [comment]
```vim
  autocmd FileType vimfiler call s:vimfiler_config()

function s:vimfiler_config()
nunmap <buffer> <Space>
nmap <buffer> <Leader> <Plug>(vimfiler_edit_file)
endifunction
```
