### ISSUE TITLE
Neovim syntax highlighting disappears

### ISSUE THREAD

**Issue by asilvadesigns** [Shougo/vimfiler.vim#397]
There is a strange issue in neovim, when filer is the only buffer visible, such that it takes up the whole screen space, the colors go away, and there are no highlight groups available. 

But when it is a split buffer, the colors come back... very strange.

Any idea what this is?

**Comment by Shougo** [comment]
Please create the minimal init.vim and the reproduce ways from neovim starting.
I will test it.

**Comment by asilvadesigns** [comment]
@Shougo issue has to do with current color scheme I'm using, sorry about that. Closing.

**Comment by Shougo** [comment]
OK.
