### ISSUE TITLE
Overwrite a default mapping?

### ISSUE THREAD

**Issue by asilvadesigns** [Shougo/vimfiler.vim#398]
Is there a way to overwrite a single key map as opposed to disabling all the defaults and setting your own? I'm trying to disable the use of 'ctrl-l' to redraw screen, as I use it to jump through buffer panes. Thank you for the help, awesome plugin!!

**Comment by Shougo** [comment]
```vim
autocmd FileType vimfiler nunmap <buffer> <C-l>
```

**Comment by asilvadesigns** [comment]
@Shougo thank you!
