### ISSUE TITLE
VimfilerExplorer command with -auto-cd flag doesn't seem to work.

### ISSUE THREAD

**Issue by asilvadesigns** [Shougo/vimfiler.vim#399]
Hi @Shougo, when I call `:VimfilerExplorer -auto-cd`, the vim directory does not change, it does change however when I use `:Vimfiler -auto-cd`. Perhaps I'm doing something wrong? I would simply like for the explorer functionality and the auto change, thanks for your help!

**Comment by Shougo** [comment]
@asilvadesigns `-auto-cd` just changes current window directory.
It does not change the other windows directory.
