### ISSUE TITLE
unnecessary window shown in explorer

### ISSUE THREAD

**Issue by estrategoreal** [Shougo/vimfiler.vim#401]
window is split unnecessrily when vim is launched as below

vim +VimFilerExplorer

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/400

It is feature.
Because `VimFilerExplorer` should be split as explorer mode.

**Comment by estrategoreal** [comment]
window is split by three as below

![screen](https://user-images.githubusercontent.com/1629190/30009166-11b19184-9161-11e7-9284-19bf83a35309.jpg)

**Comment by Shougo** [comment]
Uh, I get it.
