### ISSUE TITLE
Broken vimfiler_close

### ISSUE THREAD

**Issue by tex** [Shougo/vimfiler.vim#403]
c88a634b9575c5e162e79da154beb628374e4542 commit broke this mapping
-			<Plug>(vimfiler_close)

Before this commit, open file, open vimfiler with `VimFilerBufferDir -buffer-name=vimfiler`, close vimfiler using `-`. You are back in the opened file.
With this commit, open file, open vimfiler,with `VimFilerBufferDir -buffer-name=vimfiler`, close vimfiler using `-`. You are in empty new [No Name] file.

Intended behavior is before this commit.

**Comment by Shougo** [comment]
I cannot reprorduce the behavior with the below vimrc.
Please upload the minimal vimrc and the reproduce ways from the starting.
I will close it if you cannot upload them.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/vimfiler.vim/
set rtp+=~/.cache/dein/repos/github.com/Shougo/unite.vim/
```

**Comment by tex** [comment]
Sorry Shougo, I'm using neovim and this is minimal vimrc that shows the problem:

set rtp+=~/.vim/plugged/vimfiler.vim/
set rtp+=~/.vim/plugged/unite.vim/
set rtp+=~/.vim/plugged/vimfiler-prompt.git/

    let g:loaded_netrwPlugin = 1 " Disable netrw.vim
    let g:vimfiler_safe_mode_by_default = 0
    let g:unite_kind_file_use_trashbox = 1
    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_split_rule="botright"
    let g:vimfiler_force_overwrite_statusline = 0
    let g:vimfiler_enable_auto_cd = 0
    let g:vimfiler_time_format = "%y/%m/%d %H:%M "  " The space at the end is important (my terminal cuts off last column?...)

    nnoremap <silent> - :VimFilerBufferDir -buffer-name=vimfiler<CR>

    autocmd FileType vimfiler call s:vimfiler_settings()
    function! s:vimfiler_settings()
        nunmap <buffer> <C-i>
        nmap <buffer> i :VimFilerPrompt<CR>
    endfunction


Just open neovim, press -, select file, open it, then press -, you should see vimfiler, press -, you should be beck in the previously opened file. The commit that works and does not work is as I described.

**Comment by Shougo** [comment]
OK.  I get it.
I will fix it.

**Comment by tex** [comment]
Works. Thanks!
