### ISSUE TITLE
vimfiler#custom#profile() is not working if vim-devicons plugin installed

### ISSUE THREAD

**Issue by kutsan** [Shougo/vimfiler.vim#405]
### Summary

I kind of find the problem. As I mentioned in the title vimfiler's `vimfiler#custom#profile()` function do nothing if vim-devicons installed. Haven't tried this problem with other plugin managers.

### Example `vimrc`

```vim
call plug#begin('~/.vim/plugged')

Plug 'Shougo/unite.vim'
Plug 'Shougo/vimfiler.vim'
Plug 'ryanoasis/vim-devicons' " Comment this line.

call plug#end()

call vimfiler#custom#profile(
	\ 'default',
	\ 'context',
	\ {
	\	'explorer': 1,
	\	'status': 1,
	\	'find': 1,
	\	'safe': 0,
	\	'winwidth': 10,
	\  	'split': 1
	\ }
\ )

```

### Steps to produce

1. Use above `vimrc` without any configuration.
2. Install vim-plug and install plugins with `:PlugInstall`.
3. Type `:VimFiler` and see options haven't applied.
4. Delete or comment `Plug 'ryanoasis/vim-devicons'` line and restart vim.
5. Type `:VimFiler` and see options successfully applied.

**Comment by Shougo** [comment]
OK.  It is reproduced.
It seems vim-devicons problem.
I will check it.

**Comment by Shougo** [comment]
`let g:webdevicons_enable_vimfiler = 0` works for me without the problem.

**Comment by Shougo** [comment]
I get the reason.
I will fix it.

**Comment by kutsan** [comment]
Thank you, looking forward to! And, care to share what causes the problem briefly? Just out of curiosity.

**Comment by Shougo** [comment]
https://github.com/ryanoasis/vim-devicons/blob/4f616234ee164003c74a6b273ceb453cfb1a913a/plugin/webdevicons.vim#L474

It overwrites your configuration.

**Comment by kutsan** [comment]
Ah, thanks again.
