### ISSUE TITLE
Can't rename a directory if a file inside it is open in a buffer

### ISSUE THREAD

**Issue by shinzui** [Shougo/vimfiler.vim#406]
Renaming a directory with a file inside it open in a buffer results in the Unite error below. 

![image](https://user-images.githubusercontent.com/519/32277160-c728599a-bece-11e7-864c-f48c170f4ec5.png)

**Comment by Shougo** [comment]
This is Vim feature.

```
							*E139*  >
  File is loaded in another buffer

You are trying to write a file under a name which is also used in another
buffer.  This would result in two versions of the same file.
```
