### ISSUE TITLE
sorting issue

### ISSUE THREAD

**Issue by magicalbanana** [Shougo/vimfiler.vim#407]
I seem to have some issues when opening `vimfiler` and listing the contents of a directory. It appears that the sorting is a bit off.

![image](https://user-images.githubusercontent.com/7953984/32796218-ba2e1972-c933-11e7-9c47-3222b9d9cdbd.png)

As you can see, the dates are all over the place. What could be causing this?

**Comment by Shougo** [comment]
Please upload the directory files.
I will test it.

**Comment by Shougo** [comment]
We need the reproduce able configuration and the reproduce ways from Vim starting.
And please provide the Vim build information.

**Comment by magicalbanana** [comment]
Don't have this issue anymore. But now I have an issue where sorting isn't grouped by type. I had it before where hidden files are grouped then sorted. Now, all folders are sorted by name regardless if it's hidden or not.

**Comment by Shougo** [comment]
> Don't have this issue anymore. But now I have an issue where sorting isn't grouped by type. I had it before where hidden files are grouped then sorted. Now, all folders are sorted by name regardless if it's hidden or not.

It is the feature.
vimfiler sorting does not respect hidden files.
