### ISSUE TITLE
Colors for files depending on file type

### ISSUE THREAD

**Issue by Emigre** [Shougo/vimfiler.vim#410]
I would like to show some files with customized colors in vimfiler. For example, I would like to show `.c` files with a color of my choice, or any file starting with a dot in a dark shade of gray.

After reading the documentation and looking at the source code, I am under the impression that this is not possible. In the [relevant section of the manual](https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt#L233) it says that there are five categories defined ("text", "image", etc.) and it is possible to define the file extensions that belong to each of these categories.

I would like to be able to create new categories and define the extensions included in them, and the colors associated to each.

I have done a small fix to get this effect in my [.vimrc](https://github.com/Emigre/dotfiles/blob/master/roles/vim/files/vimfiler.vim#L21) but it does not work very well.

Is this possible at the moment in any way or would this be a new feature? I have tried to implement this myself but I am not familiar with your source code and have given up after a while.

Thank you very much for your work in this plugin, I think it's great.

**Comment by Shougo** [comment]
Sorry, I don't want to add the feature.
PR is wellcome though.

**Comment by Emigre** [comment]
Sure, no problem 👍 I could try to look into this if I have some spare time, although I'm not sure I will have it. As a simpler version, I could add some new colour categories to the existing ones, for example "python", "cpp", "stylesheet", "makefile", etc. It's just an idea, though: they don't seem as generic as the current ones ("text", "image"...), but it seems easier to implement  than to allow total customisation. It still offers a wider potential colour variety. Would that be all right?

**Comment by Shougo** [comment]
I think it should be more generic though.
I will look into the implementation.

**Comment by Emigre** [comment]
You are totally right, on second thought it's not a good idea. A user might want to colour a particular category of files but another user might prefer an entirely different group of categories. It probably has more sense for this functionality to be generic as it is now or customizable so a user can choose exactly the groups of files that he needs.

**Comment by Shougo** [comment]
>  It probably has more sense for this functionality to be generic as it is now or customizable so a user can choose exactly the groups of files that he needs.

Yes.

**Comment by Shougo** [comment]
It should be implemented in defx.nvim.

https://github.com/Shougo/defx.nvim

**Comment by Emigre** [comment]
Great, thank you very much
