### ISSUE TITLE
Improve documentation for g:unite_kind_file_use_trashbox

### ISSUE THREAD

**Issue by GloverDonovan** [Shougo/vimfiler.vim#412]
Hello,

The language is difficult to understand in this section.

https://github.com/Shougo/vimfiler.vim/blob/9deb9b4fbae6b17feb8b5da5ca1fe37391d760f3/doc/vimfiler.txt#L428-L433

Can you take a look at it?

Thanks for your hard work!

**Comment by Shougo** [comment]
@GloverDonovan You can improve it.  The pull request is wellcome.
