### ISSUE TITLE
creating file links

### ISSUE THREAD

**Issue by fab6** [Shougo/vimfiler.vim#413]
Hi,
is there any option to create a file link in linux (ln -s)?
Thanks!
Nice tool.

**Comment by Shougo** [comment]
Nothing.

You can use the command by `!`.

**Comment by fab6** [comment]
ok, thanks!
When using "!" can I easily get the current file name and e.g. the directory of the other pane of a VimFilerDouble?
Maybe something like ":! ln -s % <dir_other>

**Comment by Shougo** [comment]
`dir_other` is not supported.

current file name is automatically inserted if you have selected.

**Comment by fab6** [comment]
ok, thanks
