### ISSUE TITLE
sorting key map and toggle ascending /descending

### ISSUE THREAD

**Issue by fab6** [Shougo/vimfiler.vim#414]
Hi,
I am aware of the sorting key S in combination with the unite interface.
Is there an option to set eg. the keys ";sd" to sort for date/time and ";sn" to sort for name?
And maybe chaning the sorting direction by ";sD" and ";sN".
This would be quite helpful.
Thanks!

**Comment by fab6** [comment]
Hi,
me again, I think I am a bit closer to it... I tried to adjust the profile by using:
:call vimfiler#custom#profile('default','context',{'sort-type':'time'})

Though, this does not have any impact at all.

**Comment by Shougo** [comment]
`call vimfiler#custom#profile('default','context',{'sort_type':'time'})`

And it just change the initial sort configuration.
It is not changed dynamically.

So the feature cannot be supported.
vimfiler development is already done.

It should be supported in defx.nvim.

**Comment by Shougo** [comment]
denite already supports the feature though.

`<denite:toggle_sorters:{arg}>`

**Comment by fab6** [comment]
Thank you!
