### ISSUE TITLE
VimFiler opens a new empty buffer on quit/hide

### ISSUE THREAD

**Issue by wilywampa** [Shougo/vimfiler.vim#415]
In certain cases (e.g. opening a VimFiler buffer using `gf` after the `t:vimfiler` variable already exists) VimFiler will open up a new empty buffer when closed instead of going back to a recent buffer. Here's how to reproduce the problem:

Minimal init.vim:
```vim
set runtimepath+=/Users/jniehus/Downloads/dev/vimfiler.vim
set runtimepath+=/Users/jniehus/Downloads/dev/unite.vim
let g:vimfiler_restore_alternate_file = 0
let g:vimfiler_as_default_explorer = 1
nnoremap <silent> - :VimFilerBufferDir -find<CR>
```

Then,

1. Open `nvim ~/.config/nvim/init.vim`
2. Press `-` to open VimFiler
3. Press `Q` to close VimFiler
4. Put your cursor on a valid directory path and go `gf` to open VimFiler again
5. Press `Q` again to close VimFiler again, except this time it leaves you on a new empty buffer

I'm not exactly sure what's going on (otherwise this would be a pull request) but it has something to do with `t:vimfiler` and the new buffer is being created from https://github.com/Shougo/vimfiler.vim/blob/master/autoload/vimfiler/util.vim#L190

Thanks!

**Comment by Shougo** [comment]
Reproduced.  I will fix it.
