### ISSUE TITLE
copy files from on vimfiler-buffer to another

### ISSUE THREAD

**Issue by fab6** [Shougo/vimfiler.vim#416]
Hi,
I have often multiple directories open with vimfiler to compare visually differences among them.
Mostly, I need to copy or move some files around as well.
For this, I like that the destination path is "known", when I use "vimfiler_open_file_another_vimfiler".
Though it seems, that with this setup I am not able to open further independent vimfilers.

Opening several vimfilers work with VimFilerCreate, though for copying and pasting it seems that there is no default destination from the other vimfiler available.

Am I anything missing or does there exist a workaround for this?

Thank you!

**Comment by Shougo** [comment]
Sorry, it is not supported.

**Comment by fab6** [comment]
ok, thanks.

**Comment by fab6** [comment]
I try this now:
 nmap <buffer>C <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_copy_file)<C-w>w<Plug>(vimfiler_clipboard_paste)                                                               
 nmap <buffer>R <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_move_file)<C-w>w<Plug>(vimfiler_clipboard_paste)
