### ISSUE TITLE
<space> is used by nvim - how to remap select

### ISSUE THREAD

**Issue by FinnFrotscher** [Shougo/vimfiler.vim#417]
I am a beginner vim user (first week). 
This [tutorial](https://wrotenwrites.com/a_modern_terminal_workflow_2/)  gave me the tipp to remap the leader key to <space>
when i open vimfiler i cant use space because it selects the current file, thus i can not toggle vimfiler and am forever stuck.

how (and in what file?) to remap the space key? and what other key do you propose?

**Comment by Shougo** [comment]
```vim
autocmd FileType vimfiler call s:my_vimfiler()
function! s:my_vimfiler()
  nunmap <Space>
  nmap     <CR>   <Plug>(vimfiler_toggle_mark_current_line)
endfunction
```
