### ISSUE TITLE
git conflict mark

### ISSUE THREAD

**Issue by YueHonghui** [Shougo/vimfiler.vim#418]
In vscode, there will be a mark on the right of file name in file explorer if the file in the unmerged conflicted state of git. This feature is very useful, how can I get this with vimfiler?
<img width="156" alt="git-conflict-mark" src="https://user-images.githubusercontent.com/5221912/38169256-062dbfbe-3598-11e8-8194-30417a3d0c9d.png">

**Comment by Shougo** [comment]
You can create new column.

`:help vimfiler-columns`
