### ISSUE TITLE
Why not using denite.vim because "unite.vim" is unmaintained?

### ISSUE THREAD

**Issue by ReFleXzZ** [Shougo/vimfiler.vim#419]
The attempt running Vimfiler result's in throwing an error on me, for installing unite.vim.
Do you recommend using unite although it's unmaintained except for bug reports or is denite the better choice?

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/380

**Comment by Shougo** [comment]
vimfiler.vim is old project.
It should be rewritten.

**Comment by ReFleXzZ** [comment]
aaah okay for some reason, those issues are not showing up in the Issues list, so i didn't see them.
