### ISSUE TITLE
'matcher_ignore_wildignore' filter causing crash

### ISSUE THREAD

**Issue by slmjkdbtl** [Shougo/vimfiler.vim#421]
after setting
```viml
let g:vimfiler_ignore_filters = 'matcher_ignore_wildignore'
```
I got this from calling `VimFiler`

```
Error detected while processing function vimfiler#init#_command[22]..vimfiler#init#_
start[63]..<SNR>74_create_vimfiler_buffer[67]..vimfiler#handler#_event_handler[15]..
<SNR>99_on_BufReadCmd[23]..vimfiler#init#_vimfiler_directory[24]..vimfiler#init#_fil
ters:
line    3:
E714: List required
Error detected while processing function vimfiler#init#_command[22]..vimfiler#init#_
start[63]..<SNR>74_create_vimfiler_buffer[67]..vimfiler#handler#_event_handler[15]..
<SNR>99_on_BufReadCmd[23]..vimfiler#init#_vimfiler_directory[64]..vimfiler#view#_for
ce_redraw_all_vimfiler[10]..vimfiler#view#_force_redraw_screen[61]..vimfiler#view#_r
edraw_screen[17]..vimfiler#helper#_call_filters:
line    2:
E714: List required
Error detected while processing function vimfiler#init#_command[22]..vimfiler#init#_
start[63]..<SNR>74_create_vimfiler_buffer[67]..vimfiler#handler#_event_handler[15]..
<SNR>99_on_BufReadCmd:
line   23:
E171: Missing :endif
```

not sure about the exact cause because I have a `VimEnter` autocmd which calls VimFiler at start but that works fine, anytime after that I got the error message if I call VimFiler. 

and plus the filter is not ignoring directories defined like `wildignore+=*/.git/*`, but setting `wildignore+=.git` works

**Comment by Shougo** [comment]
`g:vimfiler_ignore_filters` must be List.

`let g:vimfiler_ignore_filters = ['matcher_ignore_wildignore']`

> and plus the filter is not ignoring directories defined like `wildignore+=*/.git/*`, but setting `wildignore+=.git` works

It is feature.  Because `*/.git/*` does not much `.git`.

Closing.
