### ISSUE TITLE
Move file functionality not working

### ISSUE THREAD

**Issue by fxdgear** [Shougo/vimfiler.vim#423]
in vimfiler I select a file to move with `m`. I then navigate to the directory I want it to move to and hit `m` again. I am prompted if "I really want to move these files [yes/no]". i type yes hit enter and nothing. I hit enter again and it says "Canceled"

**Comment by Shougo** [comment]
Hm....
I think you are wrong.

It must be:

` I select a file to move with m in vimfiler window A`
`navigate to the directory in another vimfiler window B`
`Press m key in window A`
`It will be moved`

**Comment by Shougo** [comment]
defx.nvim similar behaves your desired.
I think you should use defx.nvim instead.

**Comment by Shougo** [comment]
You can create another vimfiler window by `<Plug>(vimfiler_switch_to_another_vimfiler)`.
