### ISSUE TITLE
How do I beautify the file type icons?

### ISSUE THREAD

**Issue by mertyildiran** [Shougo/vimfiler.vim#425]
How do I beautify the **file type icons** like the screenshot that given in README.md? By "*beautify*" I mean getting rid of `[ ]` around the file type icons and showing a folder icon for the folders too.

My current status:

![](https://i.ibb.co/Lxm2Fbr/Screenshot-20190414-031142.png)

The screenshot in README.md:

![](https://user-images.githubusercontent.com/7071307/31679880-7e4d785c-b340-11e7-894e-3ea74556e491.png)

By the way I'm a SpaceVim user. :blush:

**Comment by Shougo** [comment]
You should ask it in SpaceVim.
vimfiler does not have the feature.

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/80#issuecomment-434526157

**Comment by Shougo** [comment]
I think he uses custom column.  I don't know the detail though.

**Comment by Shougo** [comment]
https://github.com/asilvadesigns/.dotfiles/blob/master/nvim/config/plugins.vim#L282

**Comment by Shougo** [comment]
https://github.com/ryanoasis/vim-devicons

It supports vimfiler.
