### ISSUE TITLE
Mapping - to go directory up

### ISSUE THREAD

**Issue by schoettl** [Shougo/vimfiler.vim#429]
Hi, thanks for this great plugin.

netrw has the `-` mapping to go one directory up. vim-vinegar provides the `-` mapping to go from a file to it's containing directory. I am used to hit `-` twice to go from a file to it's parent-parent directory.

How about changing `-` in vimfiler to also go one directory up? (`<Plug>(vimfiler_switch_to_parent_directory)`)

We can of course keep the `<BS>` mapping but use `<Esc>` (and `q`) to close vimfiler.

Would you accept a pull request for this (kind of breaking) change?

**Comment by Shougo** [comment]
I don't want to add the default key mapping.

You can change it.

**Comment by schoettl** [comment]
OK, I added it in my `~/.vim/ftplugin/vimfiler.vim`

```
nmap <buffer> - <Plug>(vimfiler_switch_to_parent_directory)
```
