### ISSUE TITLE
Vimfiler should provide more APIs and a more detailed manual

### ISSUE THREAD

**Issue by li-zyang** [Shougo/vimfiler.vim#431]
I have looked up the Vimfiler's manul several times and I think Vimfiler should provide more APIs, profile-getter for example.
And I did not fully understand what I can do with some functions like ```do_action()``` after reading the manul.
(Though the defx is more recommended, it still take some time to switch to it, and the above for defx too, maybe)
Thanks for taking into consideration.

**Comment by Shougo** [comment]
No.

Because

> Note: Active development on vimfiler.vim has stopped. The only future changes will be bug fixes.

**Comment by Shougo** [comment]
In defx, I can improve the feature.
But I think you should improve the documentation instead.
Because it is open source project.
Why you wait until the author fix the problem???
