### ISSUE TITLE
how to copy/paste files in vimfiler

### ISSUE THREAD

**Issue by johnsonkee** [Shougo/vimfiler.vim#434]
Hello, I am using SpaceVim as my vim IDE. Its file-tree plugin is vimfiler, I can use "y Y" to copy a file, but I don't know to paste the copied file. Could you tell me how to do it? Thank you!

**Comment by Shougo** [comment]
It should be asked in SpaceVim issues.
Because SpaceVim defines the configuration...

`P` is paste mapping.
It is defined in https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/config/plugins/vimfiler.vim#L99

**Comment by johnsonkee** [comment]
thank you
